//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SERVO.rc
//
#define IDC_COMBO1                      1010
#define IDC_INT                         1011

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1013
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
