#ifndef LANGUAGE_H
#define LANGUAGE_H

extern BOOL g_bEnglish;

#define SET_CONTROL_LAN(DlgID,CtrlID) if (g_bEnglish)\
	(GetDlgItem(CtrlID))->SetWindowTextA(DlgID##_##CtrlID##_TEXT_EN); \
		else\
		(GetDlgItem(CtrlID))->SetWindowTextA(DlgID##_##CtrlID##_TEXT_CN); \

#define SET_DLG_LAN(DlgID) if (g_bEnglish)\
	(this)->SetWindowTextA(DlgID##_TEXT_EN); \
		else\
		(this)->SetWindowTextA(DlgID##_TEXT_CN); \

//IDD_DLG_SELECT_LANGUAGE选择界面
//英文
#define IDD_DIG_SELECT_LANGUAGE_TEXT_EN "SelectLanguage"
#define IDD_DIG_SELECT_LANGUAGE_ID_LANGUAGE_OK_TEXT_EN "OK"
//中文
#define IDD_DIG_SELECT_LANGUAGE_TEXT_CN "选择语言"
#define IDD_DIG_SELECT_LANGUAGE_ID_LANGUAGE_OK_TEXT_CN "确定"

//IDD_DLG_CLIENT_DEMO
//英文
#define IDD_DLG_CLIENT_DEMO_IDC_STATIC_V1_TEXT_EN "Version"
#define IDD_DLG_CLIENT_DEMO_IDC_STATIC_SDKV_TEXT_EN "SDKVersion:"
#define IDD_DLG_CLIENT_DEMO_IDC_STATIC_USERINFO_TEXT_EN "LoginInfo"
#define IDD_DLG_CLIENT_DEMO_IDC_STATIC_USER_NAME_TEXT_EN "UserName:"
#define IDD_DLG_CLIENT_DEMO_IDC_STATIC_PW_TEXT_EN "Password:"
#define IDD_DLG_CLIENT_DEMO_IDC_CHK_INCLUDE_ALL_TEXT_EN "EnumThird-PrtyDevs"
#define IDD_DLG_CLIENT_DEMO_IDC_CHK_SEPARATE_TEXT_EN "AudioVideoSeparation" 
#define IDD_DLG_CLIENT_DEMO_IDC_BTN_ENUM_HID_TEXT_EN "EnumDevices"
#define IDD_DLG_CLIENT_DEMO_IDC_BTN_LOGIN_TEXT_EN "LoginDevice"
#define IDD_DLG_CLIENT_DEMO_IDC_BTN_LOGOUT_TEXT_EN "LogoutDevice"
#define IDD_DLG_CLIENT_DEMO_IDC_BTN_ACTIVE_TEXT_EN "ActivateDevice"
#define IDD_DLG_CLIENT_DEMO_IDC_BTN_SET_USER_DATA_TEXT_EN "SetUserData"
#define IDD_DLG_CLIENT_DEMO_IDC_STATIC_DEVICE_INFO_TEXT_EN "DeviceInfo"
#define IDD_DLG_CLIENT_DEMO_IDC_STATIC_DEVICE_NAME_TEXT_EN "DeviceName:"
#define IDD_DLG_CLIENT_DEMO_IDC_STATIC_DEVICE_SERIAL_TEXT_EN "Serial:"

//中文
#define IDD_DLG_CLIENT_DEMO_IDC_STATIC_V1_TEXT_CN "版本"
#define IDD_DLG_CLIENT_DEMO_IDC_STATIC_SDKV_TEXT_CN "SDK版本："
#define IDD_DLG_CLIENT_DEMO_IDC_STATIC_USERINFO_TEXT_CN "登录信息"
#define IDD_DLG_CLIENT_DEMO_IDC_STATIC_USER_NAME_TEXT_CN "用户名:"
#define IDD_DLG_CLIENT_DEMO_IDC_STATIC_PW_TEXT_CN "密码:"
#define IDD_DLG_CLIENT_DEMO_IDC_CHK_INCLUDE_ALL_TEXT_CN "枚举三方设备"
#define IDD_DLG_CLIENT_DEMO_IDC_CHK_SEPARATE_TEXT_CN "音视频分离" 
#define IDD_DLG_CLIENT_DEMO_IDC_BTN_ENUM_HID_TEXT_CN "枚举设备"
#define IDD_DLG_CLIENT_DEMO_IDC_BTN_LOGIN_TEXT_CN "登录设备"
#define IDD_DLG_CLIENT_DEMO_IDC_BTN_LOGOUT_TEXT_CN "注销设备"
#define IDD_DLG_CLIENT_DEMO_IDC_BTN_ACTIVE_TEXT_CN "激活设备"
#define IDD_DLG_CLIENT_DEMO_IDC_BTN_SET_USER_DATA_TEXT_CN "设置用户信息"
#define IDD_DLG_CLIENT_DEMO_IDC_STATIC_DEVICE_INFO_TEXT_CN "设备信息"
#define IDD_DLG_CLIENT_DEMO_IDC_STATIC_DEVICE_NAME_TEXT_CN "设备名称:"
#define IDD_DLG_CLIENT_DEMO_IDC_STATIC_DEVICE_SERIAL_TEXT_CN "序列号:"

//IDD_SUBDLG_DEV_INTERFACE
//英文
#define IDD_SUBDLG_DEV_INTERFACE_IDC_BTN_BEEP_AND_FLICKER_TEXT_EN "BuzzerAndLED"
#define IDD_SUBDLG_DEV_INTERFACE_IDC_BTN_GET_HAIRPIN_VER_TEXT_EN "Get Card Version"
#define IDD_SUBDLG_DEV_INTERFACE_IDC_BTN_RESET_RFC_TEXT_EN "RFC Reset"
#define IDD_SUBDLG_DEV_INTERFACE_IDC_BTN_UPGRADE_TEXT_EN "Upgrade"
#define IDD_SUBDLG_DEV_INTERFACE_IDC_BTN_REG_DEVICE_TEXT_EN "Reg Device"
#define IDD_SUBDLG_DEV_INTERFACE_IDC_BTN_SET_DEV_KEY_TEXT_EN "Set Device Key"

//中文
#define IDD_SUBDLG_DEV_INTERFACE_IDC_BTN_BEEP_AND_FLICKER_TEXT_CN "蜂鸣器及显示灯控制"
#define IDD_SUBDLG_DEV_INTERFACE_IDC_BTN_GET_HAIRPIN_VER_TEXT_CN "发卡器版本获取"
#define IDD_SUBDLG_DEV_INTERFACE_IDC_BTN_RESET_RFC_TEXT_CN "射频复位"
#define IDD_SUBDLG_DEV_INTERFACE_IDC_BTN_UPGRADE_TEXT_CN "设备升级"
#define IDD_SUBDLG_DEV_INTERFACE_IDC_BTN_REG_DEVICE_TEXT_CN "设备注册"
#define IDD_SUBDLG_DEV_INTERFACE_IDC_BTN_SET_DEV_KEY_TEXT_CN "设置设备密码"

//IDD_DLG_BEEP_AND_FLICKER
//英文
#define IDD_DLG_BEEP_AND_FLICKER_TEXT_EN "Buzzer And Display Lamp"
#define IDD_DLG_BEEP_AND_FLICKER_IDC_STATIC_BEEP_TYPE_TEXT_EN "BuzzerType:"
#define IDD_DLG_BEEP_AND_FLICKER_IDC_STATIC_FILCKER_TYPE_TEXT_EN "FlickerType:"
#define IDD_DLG_BEEP_AND_FLICKER_IDC_STATIC_BEEP_COUNT_TEXT_EN "BuzzerTimes:"
#define IDD_DLG_BEEP_AND_FLICKER_IDC_STATIC_FLICKER_COUNT_TEXT_EN "FlickerTimes:"
#define IDD_DLG_BEEP_AND_FLICKER_IDC_BTN_CFG_TEXT_EN "Set"


//中文
#define IDD_DLG_BEEP_AND_FLICKER_TEXT_CN "蜂鸣器及显示灯控制"
#define IDD_DLG_BEEP_AND_FLICKER_IDC_STATIC_BEEP_TYPE_TEXT_CN "蜂鸣类型:"
#define IDD_DLG_BEEP_AND_FLICKER_IDC_STATIC_FILCKER_TYPE_TEXT_CN "闪烁类型:"
#define IDD_DLG_BEEP_AND_FLICKER_IDC_STATIC_BEEP_COUNT_TEXT_CN "蜂鸣次数:"
#define IDD_DLG_BEEP_AND_FLICKER_IDC_STATIC_FLICKER_COUNT_TEXT_CN "闪烁次数:"
#define IDD_DLG_BEEP_AND_FLICKER_IDC_BTN_CFG_TEXT_CN "设置"

//IDD_DLG_GET_CARD_ISSUE_VER
//英文
#define IDD_DLG_GET_CARD_ISSUE_VER_TEXT_EN "Get Card Version"
#define IDD_DLG_GET_CARD_ISSUE_VER_IDC_STATIC_CARD_DEVICE_NAME_TEXT_EN "DeviceName:"
#define IDD_DLG_GET_CARD_ISSUE_VER_IDC_STATIC_CARD_DEVICE_SERIVAL_TEXT_EN "DeviceSerial:"
#define IDD_DLG_GET_CARD_ISSUE_VER_IDC_STATIC_SOFTWARE_VERSION_TEXT_EN "DeviceVersion:"
#define IDD_DLG_GET_CARD_ISSUE_VER_IDC_BTN_GET_TEXT_EN "Get"


//中文
#define IDD_DLG_GET_CARD_ISSUE_VER_TEXT_CN "获取发卡器版本"
#define IDD_DLG_GET_CARD_ISSUE_VER_IDC_STATIC_CARD_DEVICE_NAME_TEXT_CN "设备名称:"
#define IDD_DLG_GET_CARD_ISSUE_VER_IDC_STATIC_CARD_DEVICE_SERIVAL_TEXT_CN "设备序列号:"
#define IDD_DLG_GET_CARD_ISSUE_VER_IDC_STATIC_SOFTWARE_VERSION_TEXT_CN "软件版本号:"
#define IDD_DLG_GET_CARD_ISSUE_VER_IDC_BTN_GET_TEXT_CN "获取"

//IDD_DLG_GET_CARD_ISSUE_VER
//英文
#define IDD_DLG_RFC_RESET_TEXT_EN "RF Reset"
#define IDD_DLG_RFC_RESET_IDC_BTN_SET_TEXT_EN "RF Reset"

//中文
#define IDD_DLG_RFC_RESET_TEXT_CN "射频复位"
#define IDD_DLG_RFC_RESET_IDC_BTN_SET_TEXT_CN "射频复位"

//IDD_DLG_UPGRADE
//英文
#define IDD_DLG_UPGRADE_TEXT_EN "Device Update"
#define IDD_DLG_UPGRADE_IDC_STATIC_TEXT_TEXT_EN "(First upgrade, the timeout need set enough time)"
#define IDD_DLG_UPGRADE_IDC_STATIC_TIME_TEXT_EN "time-out"
#define IDD_DLG_UPGRADE_IDC_STATIC_SECOND_TEXT_EN "s(15-255)"
#define IDD_DLG_UPGRADE_IDC_STATIC_MODEL_ID_TEXT_EN "Mode ID"
#define IDD_DLG_UPGRADE_IDC_STATIC_PATH_TEXT_EN "Package Path："
#define IDD_DLG_UPGRADE_IDC_BTN_SELECT_TEXT_EN "Select"
#define IDD_DLG_UPGRADE_IDC_STATIC_STATUS_TEXT_EN "Status"
#define IDD_DLG_UPGRADE_IDC_STATIC_PROG_TEXT_EN "Progress"
#define IDD_DLG_UPGRADE_IDC_BTN_UPGRADE_TEXT_EN "Update"

//中文
#define IDD_DLG_UPGRADE_TEXT_CN "设备升级"
#define IDD_DLG_UPGRADE_IDC_STATIC_TEXT_TEXT_CN "(首次升级，系统可能更新驱动，若超时时间设置太小，会导致升级失败）"
#define IDD_DLG_UPGRADE_IDC_STATIC_TIME_TEXT_CN "超时时间"
#define IDD_DLG_UPGRADE_IDC_STATIC_SECOND_TEXT_CN "秒(15-255)"
#define IDD_DLG_UPGRADE_IDC_STATIC_MODEL_ID_TEXT_CN "模块ID"
#define IDD_DLG_UPGRADE_IDC_STATIC_PATH_TEXT_CN "升级包路径："
#define IDD_DLG_UPGRADE_IDC_BTN_SELECT_TEXT_CN "选择"
#define IDD_DLG_UPGRADE_IDC_STATIC_STATUS_TEXT_CN "升级状态"
#define IDD_DLG_UPGRADE_IDC_STATIC_PROG_TEXT_CN "进度"
#define IDD_DLG_UPGRADE_IDC_BTN_UPGRADE_TEXT_CN "升级"

//IDD_DLG_DEVICE_REG
//英文
#define IDD_DLG_DEVICE_REG_TEXT_EN "Device Register"
#define IDD_DLG_DEVICE_REG_IDC_STATIC_DATA_LEN_TEXT_EN "Data Length:"
#define IDD_DLG_DEVICE_REG_IDC_STATIC_DATA_TEXT_EN "Data:"
#define IDD_DLG_DEVICE_REG_IDC_BTN_REG_TEXT_EN "Register"

//中文
#define IDD_DLG_DEVICE_REG_TEXT_CN "设备注册"
#define IDD_DLG_DEVICE_REG_IDC_STATIC_DATA_LEN_TEXT_CN "返回数据长度："
#define IDD_DLG_DEVICE_REG_IDC_STATIC_DATA_TEXT_CN "返回数据内容："
#define IDD_DLG_DEVICE_REG_IDC_BTN_REG_TEXT_CN "注册"

//IDD_DLG_SET_DEV_KEY
//英文
#define IDD_DLG_SET_DEV_KEY_TEXT_EN "Set Device Key"
#define IDD_DLG_SET_DEV_KEY_IDC_STATIC_KEY_LEN_TEXT_EN "Key Length:"
#define IDD_DLG_SET_DEV_KEY_IDC_STATIC_KEY_TEXT_EN "Key:"
#define IDD_DLG_SET_DEV_KEY_IDC_BTN_SET_KEY_TEXT_EN "Set"

//中文
#define IDD_DLG_SET_DEV_KEY_TEXT_CN "设置设备秘钥"
#define IDD_DLG_SET_DEV_KEY_IDC_STATIC_KEY_LEN_TEXT_CN "秘钥长度："
#define IDD_DLG_SET_DEV_KEY_IDC_STATIC_KEY_TEXT_CN "秘钥："
#define IDD_DLG_SET_DEV_KEY_IDC_BTN_SET_KEY_TEXT_CN "设置"

//IDD_SUBDLG_GEN_INTERFACE
//英文
#define IDD_SUBDLG_GEN_INTERFACE_IDC_BTN_SET_CARD_PROTO_TEXT_EN "Set Card Proto Type"
#define IDD_SUBDLG_GEN_INTERFACE_IDC_BTN_ACTIVATE_CARD_TEXT_EN "Active"
#define IDD_SUBDLG_GEN_INTERFACE_IDC_BTN_STOP_CARD_OPER_TEXT_EN "Stop Opera"

//中文
#define IDD_SUBDLG_GEN_INTERFACE_IDC_BTN_SET_CARD_PROTO_TEXT_CN "设置操作卡协议类型"
#define IDD_SUBDLG_GEN_INTERFACE_IDC_BTN_ACTIVATE_CARD_TEXT_CN "激活卡"
#define IDD_SUBDLG_GEN_INTERFACE_IDC_BTN_STOP_CARD_OPER_TEXT_CN "终止卡操作"

//IDD_DLG_SET_CARD_PROTO
//英文
#define IDD_DLG_SET_CARD_PROTO_TEXT_EN "Set Card Protocol Type"
#define IDD_DLG_SET_CARD_PROTO_IDC_STATIC_TYPE_TEXT_EN "Proto Type:"
#define IDD_DLG_SET_CARD_PROTO_IDC_BTN_SET_TEXT_EN "Set"

//中文
#define IDD_DLG_SET_CARD_PROTO_TEXT_CN "设置卡协议类型"
#define IDD_DLG_SET_CARD_PROTO_IDC_STATIC_TYPE_TEXT_CN "卡协议类型："
#define IDD_DLG_SET_CARD_PROTO_IDC_BTN_SET_TEXT_CN "设置"

//IDD_DLG_ACTIVATE_CARD
//英文
#define IDD_DLG_ACTIVATE_CARD_TEXT_EN "Active Card"
#define IDD_DLG_ACTIVATE_CARD_IDC_STATIC_WAIT_TIME_TEXT_EN "Wait Time:"
#define IDD_DLG_ACTIVATE_CARD_IDC_STATIC_SEC_TEXT_EN "s"
#define IDD_DLG_ACTIVATE_CARD_IDC_BTN_ACTIVATE_TEXT_EN "Active"
#define IDD_DLG_ACTIVATE_CARD_IDC_STATIC_RSP_TEXT_EN "Response"
#define IDD_DLG_ACTIVATE_CARD_IDC_STATIC_PRO_TYPE_TEXT_EN "ProtoType:"
#define IDD_DLG_ACTIVATE_CARD_IDC_STATIC_SER_LEN_TEXT_EN "SerialLength:"
#define IDD_DLG_ACTIVATE_CARD_IDC_STATIC_SERIAL_TEXT_EN "Serial:"
#define IDD_DLG_ACTIVATE_CARD_IDC_STATIC_SELECT_LEN_TEXT_EN "SelectLength:"
#define IDD_DLG_ACTIVATE_CARD_IDC_STATIC_SELECT_TEXT_EN "Select:"
#define IDD_DLG_ACTIVATE_CARD_IDC_BTN_ACTIVATE2_TEXT_EN "CycleActive"
#define IDD_DLG_ACTIVATE_CARD_IDC_BTN_STOP_ACTIVATE_TEXT_EN "StopCycleActive"

//中文
#define IDD_DLG_ACTIVATE_CARD_TEXT_CN "激活卡"
#define IDD_DLG_ACTIVATE_CARD_IDC_STATIC_WAIT_TIME_TEXT_CN "操作等待时间："
#define IDD_DLG_ACTIVATE_CARD_IDC_STATIC_SEC_TEXT_CN "秒"
#define IDD_DLG_ACTIVATE_CARD_IDC_BTN_ACTIVATE_TEXT_CN "激活"
#define IDD_DLG_ACTIVATE_CARD_IDC_STATIC_RSP_TEXT_CN "设备应答"
#define IDD_DLG_ACTIVATE_CARD_IDC_STATIC_PRO_TYPE_TEXT_CN "卡协议类型："
#define IDD_DLG_ACTIVATE_CARD_IDC_STATIC_SER_LEN_TEXT_CN "序列号长度："
#define IDD_DLG_ACTIVATE_CARD_IDC_STATIC_SERIAL_TEXT_CN "序列号："
#define IDD_DLG_ACTIVATE_CARD_IDC_STATIC_SELECT_LEN_TEXT_CN "选择确认长度："
#define IDD_DLG_ACTIVATE_CARD_IDC_STATIC_SELECT_TEXT_CN "选择确认："
#define IDD_DLG_ACTIVATE_CARD_IDC_BTN_ACTIVATE2_TEXT_CN "循环激活"
#define IDD_DLG_ACTIVATE_CARD_IDC_BTN_STOP_ACTIVATE_TEXT_CN "停止循环激活"

//IDD_DLG_STOP_CARD_OPER
//英文
#define IDD_DLG_STOP_CARD_OPER_TEXT_EN "Stop Card Opera"
#define IDD_DLG_STOP_CARD_OPER_IDC_BTN_STOP_TEXT_EN "Stop Card Opera"

//中文
#define IDD_DLG_STOP_CARD_OPER_TEXT_CN "终止卡操作"
#define IDD_DLG_STOP_CARD_OPER_IDC_BTN_STOP_TEXT_CN "终止卡操作："

//IDD_SUBDLG_M1_CARD_INTERFACE
//英文
#define IDD_SUBDLG_M1_CARD_INTERFACE_IDC_BTN_M1_PWD_VERIFY_TEXT_EN "Pwd Verify"
#define IDD_SUBDLG_M1_CARD_INTERFACE_IDC_BTN_READ_BLOCK_TEXT_EN "Read Block"
#define IDD_SUBDLG_M1_CARD_INTERFACE_IDC_BTN_WRITE_BLOCK_TEXT_EN "Write Block"
#define IDD_SUBDLG_M1_CARD_INTERFACE_IDC_BTN_MOD_BLOCK_TEXT_EN "Modify Block"
#define IDD_SUBDLG_M1_CARD_INTERFACE_IDC_BTN_BLOCK_ADD_TEXT_EN "Add Block"
#define IDD_SUBDLG_M1_CARD_INTERFACE_IDC_BTN_BLOCK_MINUS_TEXT_EN "Reduce Block"
#define IDD_SUBDLG_M1_CARD_INTERFACE_IDC_BTN_EEPROM_TO_REG_TEXT_EN "Block Return"
#define IDD_SUBDLG_M1_CARD_INTERFACE_IDC_BTN_REG_TO_EEPROM_TEXT_EN "Block Transfer"
#define IDD_SUBDLG_M1_CARD_INTERFACE_IDC_BTN_MIFARE_PACK_TEXT_EN "Mifare Transfer"
#define IDD_SUBDLG_M1_CARD_INTERFACE_IDC_BTN_M1_SECTION_ENCRYPT_TEXT_EN "Block Encryption"

//中文
#define IDD_SUBDLG_M1_CARD_INTERFACE_IDC_BTN_M1_PWD_VERIFY_TEXT_CN "扇区带密码验证"
#define IDD_SUBDLG_M1_CARD_INTERFACE_IDC_BTN_READ_BLOCK_TEXT_CN "读卡指定块数据"
#define IDD_SUBDLG_M1_CARD_INTERFACE_IDC_BTN_WRITE_BLOCK_TEXT_CN "写卡指定块数据"
#define IDD_SUBDLG_M1_CARD_INTERFACE_IDC_BTN_MOD_BLOCK_TEXT_CN "指定扇区控制块修改"
#define IDD_SUBDLG_M1_CARD_INTERFACE_IDC_BTN_BLOCK_ADD_TEXT_CN "块加值"
#define IDD_SUBDLG_M1_CARD_INTERFACE_IDC_BTN_BLOCK_MINUS_TEXT_CN "块减值"
#define IDD_SUBDLG_M1_CARD_INTERFACE_IDC_BTN_EEPROM_TO_REG_TEXT_CN "块数值回传"
#define IDD_SUBDLG_M1_CARD_INTERFACE_IDC_BTN_REG_TO_EEPROM_TEXT_CN "块数值传送"
#define IDD_SUBDLG_M1_CARD_INTERFACE_IDC_BTN_MIFARE_PACK_TEXT_CN "Mifare数据透传"
#define IDD_SUBDLG_M1_CARD_INTERFACE_IDC_BTN_M1_SECTION_ENCRYPT_TEXT_CN "M1卡指定扇区加密"

//IDD_DLG_M1_PWD_VERIFY
//英文
#define IDD_DLG_M1_PWD_VERIFY_TEXT_EN "Password Verify"
#define IDD_DLG_M1_PWD_VERIFY_IDC_STATIC_PWD_TYPE_TEXT_EN "Pwd Type:"
#define IDD_DLG_M1_PWD_VERIFY_IDC_STATIC_BLOCK_ID_TEXT_EN "Block No:"
#define IDD_DLG_M1_PWD_VERIFY_IDC_STATIC_PWD_TEXT_EN "6Byte Pwd(Hex,Split By Space)"
#define IDD_DLG_M1_PWD_VERIFY_IDC_BTN_VERIFY_TEXT_EN "Verify"

//中文
#define IDD_DLG_M1_PWD_VERIFY_TEXT_CN "扇区带密码验证"
#define IDD_DLG_M1_PWD_VERIFY_IDC_STATIC_PWD_TYPE_TEXT_CN "密码类型："
#define IDD_DLG_M1_PWD_VERIFY_IDC_STATIC_BLOCK_ID_TEXT_CN "要验证密码的扇区号："
#define IDD_DLG_M1_PWD_VERIFY_IDC_STATIC_PWD_TEXT_CN "6Byte密码(16进制，以空格分割)："
#define IDD_DLG_M1_PWD_VERIFY_IDC_BTN_VERIFY_TEXT_CN "验证"

//IDD_DLG_M1_READ_BLOCK
//英文
#define IDD_DLG_M1_READ_BLOCK_TEXT_EN "Read Block"
#define IDD_DLG_M1_READ_BLOCK_IDC_STATIC_BLOCK_ADDRESS_TEXT_EN "Address:"
#define IDD_DLG_M1_READ_BLOCK_IDC_RAD_HEX_TEXT_EN "Hexadecimal"
#define IDD_DLG_M1_READ_BLOCK_IDC_RAD_TEXT_TEXT_EN "Text"
#define IDD_DLG_M1_READ_BLOCK_IDC_STATIC_BLOCK_DATA_TEXT_EN "Block Data:"
#define IDD_DLG_M1_READ_BLOCK_IDC_BTN_READ_TEXT_EN "Get"

//中文
#define IDD_DLG_M1_READ_BLOCK_TEXT_CN "读卡指定块数据"
#define IDD_DLG_M1_READ_BLOCK_IDC_STATIC_BLOCK_ADDRESS_TEXT_CN "块地址"
#define IDD_DLG_M1_READ_BLOCK_IDC_RAD_HEX_TEXT_CN "十六进制显示"
#define IDD_DLG_M1_READ_BLOCK_IDC_RAD_TEXT_TEXT_CN "文本显示"
#define IDD_DLG_M1_READ_BLOCK_IDC_STATIC_BLOCK_DATA_TEXT_CN "块数据："
#define IDD_DLG_M1_READ_BLOCK_IDC_BTN_READ_TEXT_CN "读取"

//IDD_DLG_M1_WRITE_BLOCK
//英文
#define IDD_DLG_M1_WRITE_BLOCK_TEXT_EN "(M1)Write Block"
#define IDD_DLG_M1_WRITE_BLOCK_IDC_STATIC_BLOCK_ADDRESS_TEXT_EN "Address:"
#define IDD_DLG_M1_WRITE_BLOCK_IDC_RAD_HEX_TEXT_EN "Hexadecimal"
#define IDD_DLG_M1_WRITE_BLOCK_IDC_RAD_TEXT_TEXT_EN "Text"
#define IDD_DLG_M1_WRITE_BLOCK_IDC_STATIC_BLOCK_DATA_TEXT_EN "Block Data:"
#define IDD_DLG_M1_WRITE_BLOCK_IDC_BTN_WRITE_TEXT_EN "Set"

//中文
#define IDD_DLG_M1_WRITE_BLOCK_TEXT_CN "(M1卡) 写卡指定块数据"
#define IDD_DLG_M1_WRITE_BLOCK_IDC_STATIC_BLOCK_ADDRESS_TEXT_CN "块地址"
#define IDD_DLG_M1_WRITE_BLOCK_IDC_RAD_HEX_TEXT_CN "十六进制显示"
#define IDD_DLG_M1_WRITE_BLOCK_IDC_RAD_TEXT_TEXT_CN "文本显示"
#define IDD_DLG_M1_WRITE_BLOCK_IDC_STATIC_BLOCK_DATA_TEXT_CN "块数据："
#define IDD_DLG_M1_WRITE_BLOCK_IDC_BTN_WRITE_TEXT_CN "写入"

//IDD_DLG_M1_MODIFY_SCB
//英文
#define IDD_DLG_M1_MODIFY_SCB_TEXT_EN "(M1)Modify Block"
#define IDD_DLG_M1_MODIFY_SCB_IDC_STATIC_BLOCK_NO_TEXT_EN "BlockNo[0-15]:"
#define IDD_DLG_M1_MODIFY_SCB_IDC_STATIC_PWDA_TEXT_EN "6Byte password A (hexadecimal):"
#define IDD_DLG_M1_MODIFY_SCB_IDC_STATIC_CONTROL_TEXT_EN "4Byte control bit (hexadecimal): "
#define IDD_DLG_M1_MODIFY_SCB_IDC_STATIC_PWDB_TEXT_EN "6Byte password B (hexadecimal):"
#define IDD_DLG_M1_MODIFY_SCB_IDC_BTN_MODIFY_TEXT_EN "Mod"

//中文
#define IDD_DLG_M1_MODIFY_SCB_TEXT_CN "(M1卡) 指定扇区控制块修改"
#define IDD_DLG_M1_MODIFY_SCB_IDC_STATIC_BLOCK_NO_TEXT_CN "扇区号[0-15]："
#define IDD_DLG_M1_MODIFY_SCB_IDC_STATIC_PWDA_TEXT_CN "6Byte密码A(16进制输入，空格分割)："
#define IDD_DLG_M1_MODIFY_SCB_IDC_STATIC_CONTROL_TEXT_CN "4Byte控制位(16进制输入，空格分割)："
#define IDD_DLG_M1_MODIFY_SCB_IDC_STATIC_PWDB_TEXT_CN "6Byte密码B(16进制输入，空格分割)："
#define IDD_DLG_M1_MODIFY_SCB_IDC_BTN_MODIFY_TEXT_CN "修改"

//IDD_DLG_M1_BLOCK_ADD
//英文
#define IDD_DLG_M1_BLOCK_ADD_TEXT_EN "(M1)Block Add"
#define IDD_DLG_M1_BLOCK_ADD_IDC_STATIC_ADDRESS_TEXT_EN "Address:"
#define IDD_DLG_M1_BLOCK_ADD_IDC_STATIC_DATA_TEXT_EN "Data:"
#define IDD_DLG_M1_BLOCK_ADD_IDC_BTN_OK_TEXT_EN "Ok"

//中文
#define IDD_DLG_M1_BLOCK_ADD_TEXT_CN "(M1卡) 块加值"
#define IDD_DLG_M1_BLOCK_ADD_IDC_STATIC_ADDRESS_TEXT_CN "块地址："
#define IDD_DLG_M1_BLOCK_ADD_IDC_STATIC_DATA_TEXT_CN "块加值："
#define IDD_DLG_M1_BLOCK_ADD_IDC_BTN_OK_TEXT_CN "确定"

//IDD_DLG_M1_BLOCK_MINUS
//英文
#define IDD_DLG_M1_BLOCK_MINUS_TEXT_EN "(M1)Block Reduce"
#define IDD_DLG_M1_BLOCK_MINUS_IDC_STATIC_ADDRESS_TEXT_EN "Address:"
#define IDD_DLG_M1_BLOCK_MINUS_IDC_STATIC_DATA_TEXT_EN "Data:"
#define IDD_DLG_M1_BLOCK_MINUS_IDC_BTN_OK_TEXT_EN "Ok"

//中文
#define IDD_DLG_M1_BLOCK_MINUS_TEXT_CN "(M1卡) 块减值"
#define IDD_DLG_M1_BLOCK_MINUS_IDC_STATIC_ADDRESS_TEXT_CN "块地址："
#define IDD_DLG_M1_BLOCK_MINUS_IDC_STATIC_DATA_TEXT_CN "块加值："
#define IDD_DLG_M1_BLOCK_MINUS_IDC_BTN_OK_TEXT_CN "确定"

//IDD_DLG_M1_BLOCK_TO_REG
//英文
#define IDD_DLG_M1_BLOCK_TO_REG_TEXT_EN "(M1)Block Return"
#define IDD_DLG_M1_BLOCK_TO_REG_IDC_STATIC_ADDRESS_TEXT_EN "Address:"
#define IDD_DLG_M1_BLOCK_TO_REG_IDC_BTN_OK_TEXT_EN "Ok"

//中文
#define IDD_DLG_M1_BLOCK_TO_REG_TEXT_CN "(M1卡)块数值回传"
#define IDD_DLG_M1_BLOCK_TO_REG_IDC_STATIC_ADDRESS_TEXT_CN "块地址："
#define IDD_DLG_M1_BLOCK_TO_REG_IDC_BTN_OK_TEXT_CN "确定"

//IDD_DLG_M1_REG_TO_BLOCK
//英文
#define IDD_DLG_M1_REG_TO_BLOCK_TEXT_EN "(M1)Block Transfer"
#define IDD_DLG_M1_REG_TO_BLOCK_IDC_STATIC_ADDRESS_TEXT_EN "Address:"
#define IDD_DLG_M1_REG_TO_BLOCK_IDC_BTN_OK_TEXT_EN "Ok"

//中文
#define IDD_DLG_M1_REG_TO_BLOCK_TEXT_CN "(M1卡) 块数值传送"
#define IDD_DLG_M1_REG_TO_BLOCK_IDC_STATIC_ADDRESS_TEXT_CN "块地址："
#define IDD_DLG_M1_REG_TO_BLOCK_IDC_BTN_OK_TEXT_CN "确定"

//IDD_DLG_M1_MIFARE_PACK
//英文
#define IDD_DLG_M1_MIFARE_PACK_TEXT_EN "Mifare Transfer"
#define IDD_DLG_M1_MIFARE_PACK_IDC_STATIC_DATA_LEN_TEXT_EN "DataLen(0-255):"
#define IDD_DLG_M1_MIFARE_PACK_IDC_STATIC_TIMEOUT_TEXT_EN "Timeout(0-255):"
#define IDD_DLG_M1_MIFARE_PACK_IDC_BTN_GET_TEXT_EN "Get"
#define IDD_DLG_M1_MIFARE_PACK_IDC_BTN_SET_TEXT_EN "Set"

//中文
#define IDD_DLG_M1_MIFARE_PACK_TEXT_CN "Mafare卡数据透传"
#define IDD_DLG_M1_MIFARE_PACK_IDC_STATIC_DATA_LEN_TEXT_CN "数据长度（0-255）："
#define IDD_DLG_M1_MIFARE_PACK_IDC_STATIC_TIMEOUT_TEXT_CN "超时时间(0-255)："
#define IDD_DLG_M1_MIFARE_PACK_IDC_BTN_GET_TEXT_CN "获取"
#define IDD_DLG_M1_MIFARE_PACK_IDC_BTN_SET_TEXT_CN "写入"


//IDD_DLG_M1_SECTION_ENCRYPT
//英文
#define IDD_DLG_M1_SECTION_ENCRYPT_TEXT_EN "M1Block Encryption"
#define IDD_DLG_M1_SECTION_ENCRYPT_IDC_STATIC_BLOCKID_TEXT_EN "BlockID[0-15]:"
#define IDD_DLG_M1_SECTION_ENCRYPT_IDC_STATIC_ENCRYPT_TEXT_EN "Encrypt Type:"
#define IDD_DLG_M1_SECTION_ENCRYPT_IDC_STATIC_VERIFY_PWD_TEXT_EN "6Byte Verification Key (hexadecimal):"
#define IDD_DLG_M1_SECTION_ENCRYPT_IDC_STATIC_NEW_PWD_TEXT_EN "New Pwd Type"
#define IDD_DLG_M1_SECTION_ENCRYPT_IDC_STATIC_PWDA_TEXT_EN "6Byte New Key A (hexadecimal):"
#define IDD_DLG_M1_SECTION_ENCRYPT_IDC_STATIC_CONTROL_TEXT_EN "4Byte control bit (hexadecimal):"
#define IDD_DLG_M1_SECTION_ENCRYPT_IDC_STATIC_PWDB_TEXT_EN "6Byte New Key B (hexadecimal):"
#define IDD_DLG_M1_SECTION_ENCRYPT_IDC_BTN_SEND_TEXT_EN "Set"

//中文
#define IDD_DLG_M1_SECTION_ENCRYPT_TEXT_CN "M1卡指定扇区加密"
#define IDD_DLG_M1_SECTION_ENCRYPT_IDC_STATIC_BLOCKID_TEXT_CN "扇区ID[0-15]:"
#define IDD_DLG_M1_SECTION_ENCRYPT_IDC_STATIC_ENCRYPT_TEXT_CN "验证密钥类型："
#define IDD_DLG_M1_SECTION_ENCRYPT_IDC_STATIC_VERIFY_PWD_TEXT_CN "6Byte验证密钥(16进制输入，空格分割)："
#define IDD_DLG_M1_SECTION_ENCRYPT_IDC_STATIC_NEW_PWD_TEXT_CN "新密钥类型："
#define IDD_DLG_M1_SECTION_ENCRYPT_IDC_STATIC_PWDA_TEXT_CN "6Byte新密钥A(16进制输入，空格分割)："
#define IDD_DLG_M1_SECTION_ENCRYPT_IDC_STATIC_CONTROL_TEXT_CN "4Byte控制位(16进制输入，空格分割)："
#define IDD_DLG_M1_SECTION_ENCRYPT_IDC_STATIC_PWDB_TEXT_CN "6Byte新密钥B(16进制输入，空格分割)："
#define IDD_DLG_M1_SECTION_ENCRYPT_IDC_BTN_SEND_TEXT_CN "设置"


//IDD_SUBDLG_CAMERA_INTERFACE
//中文
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_STATIC_VIDEO1_TYPE_TEXT_CN "视频属性"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_STATIC_AUDIO1_TYPE_TEXT_CN "音频属性"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_STATIC_DEV1_CFG_TEXT_CN "设备"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_STATIC_PREVIEW_CFG_TEXT_CN "预览设置"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_STATIC_PRVIEW_STREAM_TYPE_TEXT_CN "码流"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_CHK_PREVIEW_AUDIO_TEXT_CN "开启音频"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_STATIC_CAPTURE_CFG_TEXT_CN "录像设置"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_STATIC_CAPTURE_STREAM_TYPE_TEXT_CN "格式"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_STATIC_FACEDETECT_CFG_TEXT_CN "人脸识别配置"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_STATIC_CAPTURE_CFG2_TEXT_CN "回调设置"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_STATIC_CAPTURE_STREAM_TYPE2_TEXT_CN "码流"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_BTN_START_PREVIEW_TEXT_CN "开启"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_BTN_START_FACEDETECT_TEXT_CN "开启"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_BTN_START_RECORD_TEXT_CN "开启"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_BTN_START_STREAMCALLBACK_TEXT_CN "开启"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_BTN_ENUM_CAP_TEXT_CN "获取设备能力"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_BTN_SET_CONFIG_TEXT_CN "取流参数配置"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_BTN_SET_ROTATE_ANGLE_TEXT_CN "旋转"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_BTN_SNAPSHOT_TEXT_CN "拍照"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_BTN_STOP_PREVIEW_TEXT_CN "关闭"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_BTN_STOP_RECORD_TEXT_CN "关闭"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_BTN_STOP_FACEDETECT_TEXT_CN "关闭"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_BTN_STOP_STREAMCALLBACK_TEXT_CN "关闭"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_BTN_EVENTCALLBACK_TEXT_CN "插拔事件上报"

//英文
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_STATIC_VIDEO1_TYPE_TEXT_EN "Video"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_STATIC_AUDIO1_TYPE_TEXT_EN "Audio"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_STATIC_DEV1_CFG_TEXT_EN "Device"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_STATIC_PREVIEW_CFG_TEXT_EN "Preview"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_STATIC_PRVIEW_STREAM_TYPE_TEXT_EN "Type"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_CHK_PREVIEW_AUDIO_TEXT_EN "Sound"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_STATIC_CAPTURE_CFG_TEXT_EN "Record"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_STATIC_CAPTURE_STREAM_TYPE_TEXT_EN "Type"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_STATIC_FACEDETECT_CFG_TEXT_EN "Face Detect"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_STATIC_CAPTURE_CFG2_TEXT_EN "Callback"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_STATIC_CAPTURE_STREAM_TYPE2_TEXT_EN "Type"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_BTN_START_PREVIEW_TEXT_EN "Start"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_BTN_START_FACEDETECT_TEXT_EN "Start"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_BTN_START_RECORD_TEXT_EN "Start"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_BTN_START_STREAMCALLBACK_TEXT_EN "Start"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_BTN_ENUM_CAP_TEXT_EN "Enum Capability"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_BTN_SET_CONFIG_TEXT_EN "Type Config"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_BTN_SET_ROTATE_ANGLE_TEXT_EN "Rotate"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_BTN_SNAPSHOT_TEXT_EN "Snapshot"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_BTN_STOP_PREVIEW_TEXT_EN "Close"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_BTN_STOP_RECORD_TEXT_EN "Close"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_BTN_STOP_FACEDETECT_TEXT_EN "Close"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_BTN_STOP_STREAMCALLBACK_TEXT_EN "Close"
#define IDD_SUBDLG_CAMERA_INTERFACE_IDC_BTN_EVENTCALLBACK_TEXT_EN "Event Callback"


//IDD_SUBDLG_CAMERA_CONTROL
//中文
#define IDD_SUBDLG_CAMERA_CONTROL_IDC_BUTTON_GET_VIDEO_CAP_TEXT_CN "获取视频能力"
#define IDD_SUBDLG_CAMERA_CONTROL_IDC_BUTTON_SET_DEFAULT_CAP_TEXT_CN "恢复默认值"
#define IDD_SUBDLG_CAMERA_CONTROL_IDC_STATIC1_TEXT_CN "视频属性"
#define IDD_SUBDLG_CAMERA_CONTROL_IDC_STATIC2_TEXT_CN "照相机控制"
#define IDD_SUBDLG_CAMERA_CONTROL_IDC_BT_START_PREVIEW_TEXT_CN "预览"
#define IDD_SUBDLG_CAMERA_CONTROL_IDC_BT_STOP_PREVIEW_TEXT_CN "停止"
#define IDD_SUBDLG_CAMERA_CONTROL_IDC_STATIC19_TEXT_CN "自动"
#define IDD_SUBDLG_CAMERA_CONTROL_IDC_STATIC20_TEXT_CN "自动"

//英文
#define IDD_SUBDLG_CAMERA_CONTROL_IDC_BUTTON_GET_VIDEO_CAP_TEXT_EN "Enum Property"
#define IDD_SUBDLG_CAMERA_CONTROL_IDC_BUTTON_SET_DEFAULT_CAP_TEXT_EN "Reset"
#define IDD_SUBDLG_CAMERA_CONTROL_IDC_STATIC1_TEXT_EN "Video Property"
#define IDD_SUBDLG_CAMERA_CONTROL_IDC_STATIC2_TEXT_EN "Camera Control"
#define IDD_SUBDLG_CAMERA_CONTROL_IDC_BT_START_PREVIEW_TEXT_EN "Preview"
#define IDD_SUBDLG_CAMERA_CONTROL_IDC_BT_STOP_PREVIEW_TEXT_EN "Stop"
#define IDD_SUBDLG_CAMERA_CONTROL_IDC_STATIC19_TEXT_EN "Auto"
#define IDD_SUBDLG_CAMERA_CONTROL_IDC_STATIC20_TEXT_EN "Auto"


//IDD_SUBDLG_TRANSMISSION_INTERFACE
//中文
#define IDD_SUBDLG_TRANSMISSION_INTERFACE_IDOK_TEXT_CN "配置"
#define IDD_SUBDLG_TRANSMISSION_INTERFACE_IDC_STATIC_TEXT_CN "指令选择"

//英文
#define IDD_SUBDLG_TRANSMISSION_INTERFACE_IDOK_TEXT_EN "Config"
#define IDD_SUBDLG_TRANSMISSION_INTERFACE_IDC_STATIC_TEXT_EN "Command"


//IDD_SUBDLG_CPU_PSAM_CARD_INTERFACE
//中文
#define IDD_SUBDLG_CPU_PSAM_CARD_INTERFACE_IDC_BTN_PSAM_SOCK_SEL_TEXT_CN "PSAM卡座选择"
#define IDD_SUBDLG_CPU_PSAM_CARD_INTERFACE_IDC_BTN_CARD_PARAM_CFG_TEXT_CN "卡参数设置"
#define IDD_SUBDLG_CPU_PSAM_CARD_INTERFACE_IDC_BTN_RESET_CPU_CARD_TEXT_CN "CPU卡重置"
#define IDD_SUBDLG_CPU_PSAM_CARD_INTERFACE_IDC_BTN_CPU_CARD_DATA_TEXT_CN "CPU卡数据透传"
#define IDD_SUBDLG_CPU_PSAM_CARD_INTERFACE_IDC_BTN_CPU_CARD_EN_TEXT_CN "CPU卡加密配置"

//英文
#define IDD_SUBDLG_CPU_PSAM_CARD_INTERFACE_IDC_BTN_PSAM_SOCK_SEL_TEXT_EN "PSAM Sock Select"
#define IDD_SUBDLG_CPU_PSAM_CARD_INTERFACE_IDC_BTN_CARD_PARAM_CFG_TEXT_EN "Set Card Param"
#define IDD_SUBDLG_CPU_PSAM_CARD_INTERFACE_IDC_BTN_RESET_CPU_CARD_TEXT_EN "Reset CPU Card"
#define IDD_SUBDLG_CPU_PSAM_CARD_INTERFACE_IDC_BTN_CPU_CARD_DATA_TEXT_EN "CPU Card Data"
#define IDD_SUBDLG_CPU_PSAM_CARD_INTERFACE_IDC_BTN_CPU_CARD_EN_TEXT_EN "Set CPU Card Encrypt Param"

//IDD_DLG_CARD_PARAM_CFG
//中文
#define IDD_DLG_CARD_PARAM_CFG_TEXT_CN "卡参数设置"
#define IDD_DLG_CARD_PARAM_CFG_IDC_STATIC3_TEXT_CN "卡类型"
#define IDD_DLG_CARD_PARAM_CFG_IDC_STATIC_TEXT_CN "卡协议类型"
#define IDD_DLG_CARD_PARAM_CFG_IDC_BTN_SET_TEXT_CN "设置"

//英文
#define IDD_DLG_CARD_PARAM_CFG_TEXT_EN "Set Card Param"
#define IDD_DLG_CARD_PARAM_CFG_IDC_STATIC3_TEXT_EN "Card Type"
#define IDD_DLG_CARD_PARAM_CFG_IDC_STATIC_TEXT_EN "Card Protocol Type"
#define IDD_DLG_CARD_PARAM_CFG_IDC_BTN_SET_TEXT_EN "Set"


//IDD_DLG_CPU_CARD_RESET
//中文
#define IDD_DLG_CPU_CARD_RESET_TEXT_CN "CPU卡重置"
#define IDD_DLG_CPU_CARD_RESET_IDC_STATIC_TEXT_CN "返回数据长度"
#define IDD_DLG_CPU_CARD_RESET_IDC_STATIC1_TEXT_CN "返回数据"
#define IDD_DLG_CPU_CARD_RESET_IDC_BTN_RESET_TEXT_CN "重置"

//英文
#define IDD_DLG_CPU_CARD_RESET_TEXT_EN "Reset CPU Card"
#define IDD_DLG_CPU_CARD_RESET_IDC_STATIC_TEXT_EN "Return Data Length"
#define IDD_DLG_CPU_CARD_RESET_IDC_STATIC1_TEXT_EN "Return Data"
#define IDD_DLG_CPU_CARD_RESET_IDC_BTN_RESET_TEXT_EN "Reset"


//IDD_DLG_CPU_CARD_PACK
//中文
#define IDD_DLG_CPU_CARD_PACK_TEXT_CN "CPU卡数据透传"
#define IDD_DLG_CPU_CARD_PACK_IDC_STATIC_TEXT_CN "数据长度(0-255)"
#define IDD_DLG_CPU_CARD_PACK_IDC_STATIC1_TEXT_CN "超时时间(0-255)"
#define IDD_DLG_CPU_CARD_PACK_IDC_BTN_GET_TEXT_CN "读取"
#define IDD_DLG_CPU_CARD_PACK_IDC_BTN_SET_TEXT_CN "写入"

//英文
#define IDD_DLG_CPU_CARD_PACK_TEXT_EN "CPU Card Data Transmission"
#define IDD_DLG_CPU_CARD_PACK_IDC_STATIC_TEXT_EN "Data Length(0-255)"
#define IDD_DLG_CPU_CARD_PACK_IDC_STATIC1_TEXT_EN "Timeout(0-255)"
#define IDD_DLG_CPU_CARD_PACK_IDC_BTN_GET_TEXT_EN "Get"
#define IDD_DLG_CPU_CARD_PACK_IDC_BTN_SET_TEXT_EN "Set"


//IDD_DLG_CPU_CARD_ENCRYPT_CFG
//中文
#define IDD_DLG_CPU_CARD_ENCRYPT_CFG_TEXT_CN "CPU卡加密配置"
#define IDD_DLG_CPU_CARD_ENCRYPT_CFG_IDC_STATIC_TEXT_CN "卡类型"
#define IDD_DLG_CPU_CARD_ENCRYPT_CFG_IDC_STATIC_KEY_LENGTH_TEXT_CN "MF外部认证用密钥长度"
#define IDD_DLG_CPU_CARD_ENCRYPT_CFG_IDC_STATIC_KEY1_TEXT_CN "MF外部认证用密钥内容"
#define IDD_DLG_CPU_CARD_ENCRYPT_CFG_IDOK_TEXT_CN "配置"

//英文
#define IDD_DLG_CPU_CARD_ENCRYPT_CFG_TEXT_EN "CPU Card Encrypt Config"
#define IDD_DLG_CPU_CARD_ENCRYPT_CFG_IDC_STATIC_TEXT_EN "Card Type"
#define IDD_DLG_CPU_CARD_ENCRYPT_CFG_IDC_STATIC_KEY_LENGTH_TEXT_EN "Key Length"
#define IDD_DLG_CPU_CARD_ENCRYPT_CFG_IDC_STATIC_KEY1_TEXT_EN "Key Content"
#define IDD_DLG_CPU_CARD_ENCRYPT_CFG_IDOK_TEXT_EN "Config"


//IDD_SUBDLG_CERTIFICATE_INTERFACE
//中文
#define IDD_SUBDLG_CERTIFICATE_INTERFACE_IDC_BTN_GET_CERTIFICATE_INFO_TEXT_CN "身份证信息配置"
#define IDD_SUBDLG_CERTIFICATE_INTERFACE_IDC_BTN_GET_CERTIFICATE_ADD_ADDR_INFO_TEXT_CN "身份证追加地址获取"
#define IDD_SUBDLG_CERTIFICATE_INTERFACE_IDC_BTN_GET_CERTIFICATE_MAC_TEXT_CN "身份证序列号获取"
#define IDD_SUBDLG_CERTIFICATE_INTERFACE_IDC_BTN_GET_IC_CARD_NO_TEXT_CN "IC卡卡号获取"
#define IDD_SUBDLG_CERTIFICATE_INTERFACE_IDC_BTN_DETECT_CARD_TEXT_CN "检测卡片"
#define IDD_SUBDLG_CERTIFICATE_INTERFACE_IDC_BTN_GET_EXTERNAL_DEV_INFO_TEXT_CN "设备外设信息"
#define IDD_SUBDLG_CERTIFICATE_INTERFACE_IDC_BTN_FINGER_CFG_TEXT_CN "指纹操作"
#define IDD_SUBDLG_CERTIFICATE_INTERFACE_IDC_BTN_ISAPI_TRANSCONFIG_TEXT_CN "透传配置"
#define IDD_SUBDLG_CERTIFICATE_INTERFACE_IDC_BTN_ONLINECOLLECTION_TEXT_CN "在线采集"
#define IDD_SUBDLG_CERTIFICATE_INTERFACE_IDC_BTN_OFFLINECOLLECTION2_TEXT_CN "离线采集"
#define IDD_SUBDLG_CERTIFICATE_INTERFACE_IDC_BTN_HEALTH_CODE_TEXT_CN "4G扫码"

//英文
#define IDD_SUBDLG_CERTIFICATE_INTERFACE_IDC_BTN_GET_CERTIFICATE_INFO_TEXT_EN "ID Card Info Config"
#define IDD_SUBDLG_CERTIFICATE_INTERFACE_IDC_BTN_GET_CERTIFICATE_ADD_ADDR_INFO_TEXT_EN "Add Addr Info"
#define IDD_SUBDLG_CERTIFICATE_INTERFACE_IDC_BTN_GET_CERTIFICATE_MAC_TEXT_EN "ID Card Serial"
#define IDD_SUBDLG_CERTIFICATE_INTERFACE_IDC_BTN_GET_IC_CARD_NO_TEXT_EN "IC Card Number"
#define IDD_SUBDLG_CERTIFICATE_INTERFACE_IDC_BTN_DETECT_CARD_TEXT_EN "Detect Card"
#define IDD_SUBDLG_CERTIFICATE_INTERFACE_IDC_BTN_GET_EXTERNAL_DEV_INFO_TEXT_EN "External Device Info"
#define IDD_SUBDLG_CERTIFICATE_INTERFACE_IDC_BTN_FINGER_CFG_TEXT_EN "Finger Config"
#define IDD_SUBDLG_CERTIFICATE_INTERFACE_IDC_BTN_ISAPI_TRANSCONFIG_TEXT_EN "Transconfig Config"
#define IDD_SUBDLG_CERTIFICATE_INTERFACE_IDC_BTN_ONLINECOLLECTION_TEXT_EN "Online Collection"
#define IDD_SUBDLG_CERTIFICATE_INTERFACE_IDC_BTN_OFFLINECOLLECTION2_TEXT_EN "Offline Collection"
#define IDD_SUBDLG_CERTIFICATE_INTERFACE_IDC_BTN_HEALTH_CODE_TEXT_EN "4G Health Code"

//IDD_DLG_CERTIFICATE_INFO
//中文
#define IDD_DLG_CERTIFICATE_INFO_TEXT_CN "身份证信息配置"
#define IDD_DLG_CERTIFICATE_INFO_IDC_STATIC_TEXT_CN "文字信息"
#define IDD_DLG_CERTIFICATE_INFO_IDC_STATIC2_TEXT_CN "相片信息"
#define IDD_DLG_CERTIFICATE_INFO_IDC_STATIC3_TEXT_CN "指纹信息"
#define IDD_DLG_CERTIFICATE_INFO_IDC_STATIC4_TEXT_CN "证件类型"
#define IDD_DLG_CERTIFICATE_INFO_IDC_BTN_GET_TEXT_CN "获取"
#define IDD_DLG_CERTIFICATE_INFO_IDC_BTN_SET_TEXT_CN "设置"
#define IDD_DLG_CERTIFICATE_INFO_IDC_STATIC5_TEXT_CN "设置时不会下发文字信息"

//英文
#define IDD_DLG_CERTIFICATE_INFO_TEXT_EN "ID Card Info"
#define IDD_DLG_CERTIFICATE_INFO_IDC_STATIC_TEXT_EN "Text Info"
#define IDD_DLG_CERTIFICATE_INFO_IDC_STATIC2_TEXT_EN "Photo Info"
#define IDD_DLG_CERTIFICATE_INFO_IDC_STATIC3_TEXT_EN "Finger Info"
#define IDD_DLG_CERTIFICATE_INFO_IDC_STATIC4_TEXT_EN "Type"
#define IDD_DLG_CERTIFICATE_INFO_IDC_BTN_GET_TEXT_EN "Get"
#define IDD_DLG_CERTIFICATE_INFO_IDC_BTN_SET_TEXT_EN "Set"
#define IDD_DLG_CERTIFICATE_INFO_IDC_STATIC5_TEXT_EN "Text messages will not be distributed during setting"


//IDD_DLG_CERTIFICATE_ADD_ADDR_INFO
//中文
#define IDD_DLG_CERTIFICATE_ADD_ADDR_INFO_TEXT_CN "身份证追加地址获取"
#define IDD_DLG_CERTIFICATE_ADD_ADDR_INFO_IDC_STATIC1_TEXT_CN "追加住址信息"
#define IDD_DLG_CERTIFICATE_ADD_ADDR_INFO_IDC_BTN_GET_TEXT_CN "获取"

//英文
#define IDD_DLG_CERTIFICATE_ADD_ADDR_INFO_TEXT_EN "Get Additional Address of ID card"
#define IDD_DLG_CERTIFICATE_ADD_ADDR_INFO_IDC_STATIC1_TEXT_EN "Add Address Info"
#define IDD_DLG_CERTIFICATE_ADD_ADDR_INFO_IDC_BTN_GET_TEXT_EN "Get"


//IDD_DLG_CERTIFICATE_MAC
//中文
#define IDD_DLG_CERTIFICATE_MAC_TEXT_CN "身份证物理序列号获取"
#define IDD_DLG_CERTIFICATE_MAC_IDC_STATIC1_TEXT_CN "身份证物理序列号"
#define IDD_DLG_CERTIFICATE_MAC_IDC_BTN_GET_TEXT_CN "获取"

//英文
#define IDD_DLG_CERTIFICATE_MAC_TEXT_EN "Get Serial Number of ID card"
#define IDD_DLG_CERTIFICATE_MAC_IDC_STATIC1_TEXT_EN "Serial Number"
#define IDD_DLG_CERTIFICATE_MAC_IDC_BTN_GET_TEXT_EN "Get"


//IDD_DLG_IC_CARD_NO
//中文
#define IDD_DLG_IC_CARD_NO_TEXT_CN "IC卡卡号获取"
#define IDD_DLG_IC_CARD_NO_IDC_STATIC1_TEXT_CN "IC卡卡号"
#define IDD_DLG_IC_CARD_NO_IDC_BTN_GET_TEXT_CN "获取"

//英文
#define IDD_DLG_IC_CARD_NO_TEXT_EN "IC Card Number"
#define IDD_DLG_IC_CARD_NO_IDC_STATIC1_TEXT_EN "IC Card No"
#define IDD_DLG_IC_CARD_NO_IDC_BTN_GET_TEXT_EN "Get"

//IDD_DLG_DETECT_CARD
//中文
#define IDD_DLG_DETECT_CARD_TEXT_CN "检测卡片"
#define IDD_DLG_DETECT_CARD_IDC_STATIC_TEXT_CN "操作等待时间"
#define IDD_DLG_DETECT_CARD_IDC_STATIC1_TEXT_CN "结果"
#define IDD_DLG_DETECT_CARD_IDC_BTN_DETECT_TEXT_CN "检测"

//英文
#define IDD_DLG_DETECT_CARD_TEXT_EN "Detect Card"
#define IDD_DLG_DETECT_CARD_IDC_STATIC_TEXT_EN "Timeout"
#define IDD_DLG_DETECT_CARD_IDC_STATIC1_TEXT_EN "Result"
#define IDD_DLG_DETECT_CARD_IDC_BTN_DETECT_TEXT_EN "Detect"


//IDD_DLG_EXTERNAL_DEV
//中文
#define IDD_DLG_EXTERNAL_DEV_TEXT_CN "设备外设信息"
#define IDD_DLG_EXTERNAL_DEV_IDC_STATIC1_TEXT_CN "指纹模组软件版本"
#define IDD_DLG_EXTERNAL_DEV_IDC_STATIC2_TEXT_CN "指纹模组序列号"
#define IDD_DLG_EXTERNAL_DEV_IDC_STATIC3_TEXT_CN "安全模块序列号"
#define IDD_DLG_EXTERNAL_DEV_IDC_BTN_GET_TEXT_CN "获取"

//英文
#define IDD_DLG_EXTERNAL_DEV_TEXT_EN "External Device"
#define IDD_DLG_EXTERNAL_DEV_IDC_STATIC1_TEXT_EN "Version"
#define IDD_DLG_EXTERNAL_DEV_IDC_STATIC2_TEXT_EN "Fingerprint SN"
#define IDD_DLG_EXTERNAL_DEV_IDC_STATIC3_TEXT_EN "Security SN"
#define IDD_DLG_EXTERNAL_DEV_IDC_BTN_GET_TEXT_EN "Get"


//IDD_DLG_FINGER_PRINT
//中文
#define IDD_DLG_FINGER_PRINT_TEXT_CN "指纹"
#define IDD_DLG_FINGER_PRINT_IDC_STATIC1_TEXT_CN "设置指纹参数"
#define IDD_DLG_FINGER_PRINT_IDC_STATIC2_TEXT_CN "获取指纹比对结果"
#define IDD_DLG_FINGER_PRINT_IDC_STATIC3_TEXT_CN "比对模式"
#define IDD_DLG_FINGER_PRINT_IDC_STATIC4_TEXT_CN "比对结果"
#define IDD_DLG_FINGER_PRINT_IDC_STATIC5_TEXT_CN "采集类型"
#define IDD_DLG_FINGER_PRINT_IDC_STATIC6_TEXT_CN "模板质量"
#define IDD_DLG_FINGER_PRINT_IDC_STATIC7_TEXT_CN "超时时间"
#define IDD_DLG_FINGER_PRINT_IDC_STATIC8_TEXT_CN "匹配等级"
#define IDD_DLG_FINGER_PRINT_IDC_STATIC9_TEXT_CN "指纹采集"
#define IDD_DLG_FINGER_PRINT_IDC_STATIC10_TEXT_CN "等待时间"
#define IDD_DLG_FINGER_PRINT_IDC_STATIC11_TEXT_CN "秒"
#define IDD_DLG_FINGER_PRINT_IDC_STATIC12_TEXT_CN "指纹类型"
#define IDD_DLG_FINGER_PRINT_IDC_STATIC13_TEXT_CN "采集结果"
#define IDD_DLG_FINGER_PRINT_IDC_STATIC14_TEXT_CN "模板质量"
#define IDD_DLG_FINGER_PRINT_IDC_BTN_SET_TEXT_CN "设置"
#define IDD_DLG_FINGER_PRINT_IDC_BTN_GET_TEXT_CN "获取"
#define IDD_DLG_FINGER_PRINT_IDC_BTN_CAPTURE_TEXT_CN "采集"

//英文
#define IDD_DLG_FINGER_PRINT_TEXT_EN "Fingerprint"
#define IDD_DLG_FINGER_PRINT_IDC_STATIC1_TEXT_EN "Set"
#define IDD_DLG_FINGER_PRINT_IDC_STATIC2_TEXT_EN "Results"
#define IDD_DLG_FINGER_PRINT_IDC_STATIC3_TEXT_EN "Mode"
#define IDD_DLG_FINGER_PRINT_IDC_STATIC4_TEXT_EN "Results"
#define IDD_DLG_FINGER_PRINT_IDC_STATIC5_TEXT_EN "Type"
#define IDD_DLG_FINGER_PRINT_IDC_STATIC6_TEXT_EN "Quality"
#define IDD_DLG_FINGER_PRINT_IDC_STATIC7_TEXT_EN "Timeout"
#define IDD_DLG_FINGER_PRINT_IDC_STATIC8_TEXT_EN "Level"
#define IDD_DLG_FINGER_PRINT_IDC_STATIC9_TEXT_EN "Fingerprint Capturing"
#define IDD_DLG_FINGER_PRINT_IDC_STATIC10_TEXT_EN "Timeout"
#define IDD_DLG_FINGER_PRINT_IDC_STATIC11_TEXT_EN "s"
#define IDD_DLG_FINGER_PRINT_IDC_STATIC12_TEXT_EN "Type"
#define IDD_DLG_FINGER_PRINT_IDC_STATIC13_TEXT_EN "Results"
#define IDD_DLG_FINGER_PRINT_IDC_STATIC14_TEXT_EN "Quality"
#define IDD_DLG_FINGER_PRINT_IDC_BTN_SET_TEXT_EN "Set"
#define IDD_DLG_FINGER_PRINT_IDC_BTN_GET_TEXT_EN "Get"
#define IDD_DLG_FINGER_PRINT_IDC_BTN_CAPTURE_TEXT_EN "Capture"


//IDD_DLG_TRANSCONFIG
//中文
#define IDD_DLG_TRANSCONFIG_TEXT_CN "指纹"
#define IDD_DLG_TRANSCONFIG_IDC_STATIC1_TEXT_CN "请求类型"
#define IDD_DLG_TRANSCONFIG_IDC_STATIC2_TEXT_CN "文件全路径"
#define IDD_DLG_TRANSCONFIG_IDC_STATIC3_TEXT_CN "请求URL"
#define IDD_DLG_TRANSCONFIG_IDC_STATIC4_TEXT_CN "输入参数"
#define IDD_DLG_TRANSCONFIG_IDC_STATIC5_TEXT_CN "输出参数"
#define IDD_DLG_TRANSCONFIG_IDC_STATIC6_TEXT_CN "超时时间"
#define IDD_DLG_TRANSCONFIG_IDC_BUTTON_OPERATION_TEXT_CN "操作"
#define IDD_DLG_TRANSCONFIG_IDC_BUTTON_EXIT_TEXT_CN "退出"
#define IDD_DLG_TRANSCONFIG_IDC_CHECK2_TEXT_CN "入参读入文件数据"


//英文
#define IDD_DLG_TRANSCONFIG_TEXT_EN "Fingerprint"
#define IDD_DLG_TRANSCONFIG_IDC_STATIC1_TEXT_EN "Type"
#define IDD_DLG_TRANSCONFIG_IDC_STATIC2_TEXT_EN "Path"
#define IDD_DLG_TRANSCONFIG_IDC_STATIC3_TEXT_EN "URL"
#define IDD_DLG_TRANSCONFIG_IDC_STATIC4_TEXT_EN "Input"
#define IDD_DLG_TRANSCONFIG_IDC_STATIC5_TEXT_EN "Output"
#define IDD_DLG_TRANSCONFIG_IDC_STATIC6_TEXT_EN "Timeout"
#define IDD_DLG_TRANSCONFIG_IDC_BUTTON_OPERATION_TEXT_EN "Operation"
#define IDD_DLG_TRANSCONFIG_IDC_BUTTON_EXIT_TEXT_EN "Exit"
#define IDD_DLG_TRANSCONFIG_IDC_CHECK2_TEXT_EN "Input parameter read in file data"


//IDD_DLG_ONLINECAPTURE
//中文
#define IDD_DLG_ONLINECAPTURE_TEXT_CN "在线采集"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC1_TEXT_CN "规则配置"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC200_TEXT_CN "姓名"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC300_TEXT_CN "卡序列号长度自适应"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC400_TEXT_CN "超时时间"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC500_TEXT_CN "卡序列号长度"
#define IDD_DLG_ONLINECAPTURE_IDC_RADIO_LENAUTOOPEN_TEXT_CN "开启"
#define IDD_DLG_ONLINECAPTURE_IDC_RADIO_LENAUTOCLOSE_TEXT_CN "关闭"
#define IDD_DLG_ONLINECAPTURE_IDC_BUTTON_PRESET_TEXT_CN "配置"

#define IDD_DLG_ONLINECAPTURE_IDC_STATIC600_TEXT_CN "采集卡信息"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC700_TEXT_CN "卡号"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC800_TEXT_CN "卡类型"
#define IDD_DLG_ONLINECAPTURE_IDC_BUTTON_CAPTURECARD_TEXT_CN "开始采集"

#define IDD_DLG_ONLINECAPTURE_IDC_STATIC900_TEXT_CN "采集身份证信息"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC1000_TEXT_CN "中文姓名"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC1100_TEXT_CN "英文姓名"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC1200_TEXT_CN "性别"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC1300_TEXT_CN "出生日期"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC1400_TEXT_CN "住址"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC1500_TEXT_CN "身份证号码"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC1600_TEXT_CN "签发机关"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC1700_TEXT_CN "有效期起始时间"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC1800_TEXT_CN "有效期截止时间"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC1900_TEXT_CN "民族"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC2000_TEXT_CN "通行证号码"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC2100_TEXT_CN "签发次数"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC2200_TEXT_CN "证件类型识别"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC2300_TEXT_CN "永久居留证号码"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC2400_TEXT_CN "国籍或地区代码"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC2500_TEXT_CN "证件版本号"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC2600_TEXT_CN "受理机关代码"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC2700_TEXT_CN "指纹数量"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC2800_TEXT_CN "有无证件相片"
#define IDD_DLG_ONLINECAPTURE_IDC_BUTTON_IDDATAPATH_TEXT_CN "打开文件夹"
#define IDD_DLG_ONLINECAPTURE_IDC_BUTTON_CAPTUREIDINFO_TEXT_CN "开始采集"

#define IDD_DLG_ONLINECAPTURE_IDC_STATIC2900_TEXT_CN "采集人脸信息"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC3000_TEXT_CN "同时采集红外图片"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC3100_TEXT_CN "采集图片数据类型"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC3200_TEXT_CN "采集进度"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC3300_TEXT_CN "人脸数据"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC3400_TEXT_CN "红外人脸"
#define IDD_DLG_ONLINECAPTURE_IDC_BUTTON_FACEDATA_TEXT_CN "打开文件夹"
#define IDD_DLG_ONLINECAPTURE_IDC_BUTTON_CAPTUREFACE_TEXT_CN "开始采集"

#define IDD_DLG_ONLINECAPTURE_IDC_STATIC3500_TEXT_CN "采集指纹"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC3600_TEXT_CN "手指编号"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC3700_TEXT_CN "采集结果"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC3800_TEXT_CN "指纹质量"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC3900_TEXT_CN "手指编号"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC4000_TEXT_CN "采集结果"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC4100_TEXT_CN "指纹质量"
#define IDD_DLG_ONLINECAPTURE_IDC_BUTTON_FINGERDATA_TEXT_CN "打开文件夹"
#define IDD_DLG_ONLINECAPTURE_IDC_BUTTON_CAPTUREFINGER_TEXT_CN "开始采集"

#define IDD_DLG_ONLINECAPTURE_IDCANCEL_TEXT_CN "退出"

//英文
#define IDD_DLG_ONLINECAPTURE_TEXT_EN "Online Collection"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC1_TEXT_EN "Rule Configuration"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC200_TEXT_EN "Name"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC300_TEXT_EN "Length Adaptation"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC400_TEXT_EN "Timeout"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC500_TEXT_EN "SN Length"
#define IDD_DLG_ONLINECAPTURE_IDC_RADIO_LENAUTOOPEN_TEXT_EN "Open"
#define IDD_DLG_ONLINECAPTURE_IDC_RADIO_LENAUTOCLOSE_TEXT_EN "Close"
#define IDD_DLG_ONLINECAPTURE_IDC_BUTTON_PRESET_TEXT_EN "Set"

#define IDD_DLG_ONLINECAPTURE_IDC_STATIC600_TEXT_EN "Card Information"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC700_TEXT_EN "Card Number"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC800_TEXT_EN "Type"
#define IDD_DLG_ONLINECAPTURE_IDC_BUTTON_CAPTURECARD_TEXT_EN "Capture"

#define IDD_DLG_ONLINECAPTURE_IDC_STATIC900_TEXT_EN "Collect ID Card Information"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC1000_TEXT_EN "Chinese Name"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC1100_TEXT_EN "English Name"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC1200_TEXT_EN "Sex"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC1300_TEXT_EN "Date of Birth"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC1400_TEXT_EN "Address"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC1500_TEXT_EN "ID card No."
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC1600_TEXT_EN "Department"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC1700_TEXT_EN "Start Time"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC1800_TEXT_EN "Deadline"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC1900_TEXT_EN "Nation"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC2000_TEXT_EN "Pass Number"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC2100_TEXT_EN "Number of issues"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC2200_TEXT_EN "Certificate Type"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC2300_TEXT_EN "Residence No"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC2400_TEXT_EN "Code"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC2500_TEXT_EN "Version"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC2600_TEXT_EN "Code"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC2700_TEXT_EN "Fingerprints"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC2800_TEXT_EN "ID photos"
#define IDD_DLG_ONLINECAPTURE_IDC_BUTTON_IDDATAPATH_TEXT_EN "Folder"
#define IDD_DLG_ONLINECAPTURE_IDC_BUTTON_CAPTUREIDINFO_TEXT_EN "Capture"

#define IDD_DLG_ONLINECAPTURE_IDC_STATIC2900_TEXT_EN "Collect Face Information"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC3000_TEXT_EN "Infrared picture"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC3100_TEXT_EN "Type"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC3200_TEXT_EN "Progress"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC3300_TEXT_EN "Face data"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC3400_TEXT_EN "Infrared face"
#define IDD_DLG_ONLINECAPTURE_IDC_BUTTON_FACEDATA_TEXT_EN "Folder"
#define IDD_DLG_ONLINECAPTURE_IDC_BUTTON_CAPTUREFACE_TEXT_EN "Capture"

#define IDD_DLG_ONLINECAPTURE_IDC_STATIC3500_TEXT_EN "Collect Fingerprints"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC3600_TEXT_EN "Finger number"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC3700_TEXT_EN "Result"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC3800_TEXT_EN "Quality"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC3900_TEXT_EN "Finger number"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC4000_TEXT_EN "Result"
#define IDD_DLG_ONLINECAPTURE_IDC_STATIC4100_TEXT_EN "Quality"
#define IDD_DLG_ONLINECAPTURE_IDC_BUTTON_FINGERDATA_TEXT_EN "Folder"
#define IDD_DLG_ONLINECAPTURE_IDC_BUTTON_CAPTUREFINGER_TEXT_EN "Capture"

#define IDD_DLG_ONLINECAPTURE_IDCANCEL_TEXT_EN "Exit"



//IDD_DLG_OFFLINECAPTURE
//中文
#define IDD_DLG_OFFLINECAPTURE_TEXT_CN "离线采集"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC1_TEXT_CN "规则配置"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC2_TEXT_CN "管理员权限"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC3_TEXT_CN "卡序列号长度自适应"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC4_TEXT_CN "数据类型"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC5_TEXT_CN "采集显示"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC6_TEXT_CN "唯一性校验"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC7_TEXT_CN "长度"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC8_TEXT_CN "采集数量"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC9_TEXT_CN "姓名"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC10_TEXT_CN "工号"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC11_TEXT_CN "身份证号"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC120_TEXT_CN "身份证序列号"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC130_TEXT_CN "身份证详细信息"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC140_TEXT_CN "卡"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC150_TEXT_CN "人脸"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC160_TEXT_CN "指纹"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC170_TEXT_CN "全部"
#define IDD_DLG_OFFLINECAPTURE_IDC_BUTTON_RULECFG_TEXT_CN "配置"
#define IDD_DLG_OFFLINECAPTURE_IDC_BUTTON_INFOFILETEMPLATE_TEXT_CN "下载离线模板"
#define IDD_DLG_OFFLINECAPTURE_IDCANCEL_TEXT_CN "取消"

//英文
#define IDD_DLG_OFFLINECAPTURE_TEXT_EN "Offline Collection"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC1_TEXT_EN "Rule Configuration"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC2_TEXT_EN "Administrator permission"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC3_TEXT_EN "Length Adaptation"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC4_TEXT_EN "Type"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC5_TEXT_EN "Display"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC6_TEXT_EN "Uniqueness check"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC7_TEXT_EN "Length"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC8_TEXT_EN "Number"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC9_TEXT_EN "Name"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC10_TEXT_EN "Job Number"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC11_TEXT_EN "ID Number"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC120_TEXT_EN "ID SN"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC130_TEXT_EN "Info"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC140_TEXT_EN "Card"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC150_TEXT_EN "Face"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC160_TEXT_EN "Fingerprint"
#define IDD_DLG_OFFLINECAPTURE_IDC_STATIC170_TEXT_EN "Total"
#define IDD_DLG_OFFLINECAPTURE_IDC_BUTTON_RULECFG_TEXT_EN "Set"
#define IDD_DLG_OFFLINECAPTURE_IDC_BUTTON_INFOFILETEMPLATE_TEXT_EN "Download offline template"
#define IDD_DLG_OFFLINECAPTURE_IDCANCEL_TEXT_EN "Close"



//IDD_SUBDLG_CERTIFICATE_INTERFACE
//中文
#define IDD_SUBDLG_THERMAL_INTERFACE_IDC_STATIC1_TEXT_CN "预览"
#define IDD_SUBDLG_THERMAL_INTERFACE_IDC_STATIC2_TEXT_CN "解码方式"
#define IDD_SUBDLG_THERMAL_INTERFACE_IDC_STATIC3_TEXT_CN "配置"
#define IDD_SUBDLG_THERMAL_INTERFACE_IDC_STATIC4_TEXT_CN "选择配置功能"
#define IDD_SUBDLG_THERMAL_INTERFACE_IDC_STATIC5_TEXT_CN "选择导入文件"
#define IDD_SUBDLG_THERMAL_INTERFACE_IDC_BUTTON_SELECT_TEXT_CN "选择"
#define IDD_SUBDLG_THERMAL_INTERFACE_IDC_BUTTON_CONFIG_TEXT_CN "配置"
#define IDD_SUBDLG_THERMAL_INTERFACE_IDC_BUTTON_STOP_PREVIEW_TEXT_CN "停止"
#define IDD_SUBDLG_THERMAL_INTERFACE_IDC_BUTTON_START_PREVIEW_TEXT_CN "开始"

//英文
#define IDD_SUBDLG_THERMAL_INTERFACE_IDC_STATIC1_TEXT_EN "Preview"
#define IDD_SUBDLG_THERMAL_INTERFACE_IDC_STATIC2_TEXT_EN "Decoding Type"
#define IDD_SUBDLG_THERMAL_INTERFACE_IDC_STATIC3_TEXT_EN "Config"
#define IDD_SUBDLG_THERMAL_INTERFACE_IDC_STATIC4_TEXT_EN "Function"
#define IDD_SUBDLG_THERMAL_INTERFACE_IDC_STATIC5_TEXT_EN "File"
#define IDD_SUBDLG_THERMAL_INTERFACE_IDC_BUTTON_SELECT_TEXT_EN "Path"
#define IDD_SUBDLG_THERMAL_INTERFACE_IDC_BUTTON_CONFIG_TEXT_EN "Config"
#define IDD_SUBDLG_THERMAL_INTERFACE_IDC_BUTTON_STOP_PREVIEW_TEXT_EN "Stop"
#define IDD_SUBDLG_THERMAL_INTERFACE_IDC_BUTTON_START_PREVIEW_TEXT_EN "Start"


#endif // LANGUAGE_H