//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 ClientDemo.rc 使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_USBDEMO_DIALOG              102
#define IDD_DLG_CLIENT_DEMO             102
#define IDD_SUBDLG_CAMERA_CONTROL       103
#define IDD_SUBDLG_TRANSMISSION_INTERFACE 104
#define IDR_MAINFRAME                   128
#define IDD_SUBDLG_DEV_INTERFACE        129
#define IDD_SUBDLG_GEN_INTERFACE        131
#define IDD_SUBDLG_M1_CARD_INTERFACE    132
#define IDD_SUBDLG_CPU_PSAM_CARD_INTERFACE 133
#define IDD_DLG_BEEP_AND_FLICKER        134
#define IDD_DLG_GET_CARD_ISSUE_VER      135
#define IDD_DLG_RFC_RESET               136
#define IDD_DLG_DEVICE_REG              137
#define IDD_DLG_SET_DEV_KEY             138
#define IDD_DLG_SET_CARD_PROTO          139
#define IDD_DLG_ACTIVATE_CARD           140
#define IDD_DLG_M1_PWD_VERIFY           141
#define IDD_DLG_M1_READ_BLOCK           142
#define IDD_DLG_M1_WRITE_BLOCK          143
#define IDD_DLG_M1_MODIFY_SCB           144
#define IDD_DLG_M1_BLOCK_ADD            145
#define IDD_DLG_M1_BLOCK_MINUS          146
#define IDD_DLG_M1_EEPROM_2_REG         147
#define IDD_DLG_M1_BLOCK_TO_REG         147
#define IDD_DLG_M1_REG_2_EEPROM         148
#define IDD_DLG_M1_REG_TO_BLOCK         148
#define IDD_DLG_M1_STOP_CARD_OPER       149
#define IDD_DLG_STOP_CARD_OPER          149
#define IDD_DLG_PSAM_SOCKET_CFG         150
#define IDD_DLG_CARD_PARAM_CFG          151
#define IDD_DLG_CPU_CARD_RESET          152
#define IDD_DLG_M1_MIFARE_PACK          153
#define IDD_DLG_CPU_CARD_PACK           155
#define IDD_DLG_UPGRADE                 157
#define IDD_SUBDLG_CERTIFICATE_INTERFACE 158
#define IDD_DLG_CERTIFICATE_INFO        159
#define IDD_DLG_CERTIFICATE_ADD_ADDR_INFO 160
#define IDD_DLG_CERTIFICATE_MAC         161
#define IDD_DLG_IC_CARD_NO              162
#define IDD_DLG_DETECT_CARD             163
#define IDD_DLG_EXTERNAL_DEV            165
#define IDD_DLG_FINGER_PRINT            166
#define IDD_DLG_STATE_SECRET_PUBLISH    167
#define IDD_DLG_CPU_CARD_ENCRYPT_CFG    169
#define IDD_DLG_CPU_CARD_ENCRYPT_CFG9   170
#define IDD_DLG_M1_SECTION_ENCRYPT      171
#define IDD_DLG_TRANSCONFIG             172
#define IDD_SUBDLG_THERMAL_INTERFACE    174
#define IDD_DLG_ONLINECAPTURE           175
#define IDD_SUBDLG_CAMERA_INTERFACE     176
#define IDD_DLG_OFFLINECAPTURE          177
#define IDD_DIG_SELECT_LANGUAGE         187
#define IDD_DLG_4G_HEALTH_CODE          188
#define IDD_DLG_FILE_TRANSFER           189
#define IDC_BUTTON_STOP_PREVIEW         1000
#define IDC_LST_HID_DEV_INFO            1001
#define IDC_BTN_ENUM_HID                1002
#define IDC_BTN_SET_ROTATE_ANGLE        1002
#define IDC_BTN_ENUM_CAP                1003
#define IDC_BTN_SET_CONFIG              1004
#define IDC_STATIC_PREVIEW              1007
#define IDC_BTN_LOGIN                   1009
#define IDC_BUTTON_START_PREVIEW        1009
#define IDC_BTN_LOGOUT                  1010
#define IDC_COMBO_CONFIG                1010
#define IDC_COM_VIDEO_TYPE              1010
#define IDC_BUTTON_CONFIG               1011
#define IDC_BTN_SNAPSHOT                1011
#define IDC_BUTTON_CONFIG_STATE         1011
#define IDC_BTN_ACTIVE                  1012
#define IDC_EDIT_FILE                   1012
#define IDC_BTN_EVENTCALLBACK           1012
#define IDC_BUTTON_SELECT               1013
#define IDC_EDT_INFO                    1014
#define IDC_BUTTON_CONFIG              1014
#define IDC_STATIC_PREVIEW_WINDOW       1015
#define IDC_COM_PREVIEW_TYPE            1016
#define IDC_COM_RECORD_TYPE             1017
#define IDC_CHK_CAPTURE_AUDIO           1020
#define IDC_BTN_CARD_PARAM_CFG          1021
#define IDC_CHK_PREVIEW_AUDIO           1021
#define IDC_BTN_RESET_CPU_CARD          1022
#define IDC_BTN_CPU_CARD_DATA           1023
#define IDC_BTN_BLOCK_ADD               1024
#define IDC_COM_AUDIO_TYPE              1025
#define IDC_BTN_PSAM_SOCK_SEL           1026
#define IDC_BTN_BLOCK_MINUS             1027
#define IDC_BTN_EEPROM_TO_REG           1028
#define IDC_BTN_REG_TO_EEPROM           1029
#define IDC_BTN_STOP_CARD_OPER          1030
#define IDC_BTN_MIFARE_PACK             1031
#define IDC_TAB_MAIN                    1032
#define IDC_STATIC_PRVIEW_STREAM_TYPE   1032
#define IDC_BTN_BEEP_AND_FLICKER        1033
#define IDC_BTN_GET_HAIRPIN_VER         1034
#define IDC_BTN_RESET_RFC               1035
#define IDC_STATIC_PREVIEW_CFG          1035
#define IDC_BTN_REG_DEVICE              1036
#define IDC_STATIC_CAPTURE_STREAM_TYPE  1036
#define IDC_BTN_SET_CARD_PROTO          1037
#define IDC_STATIC_CAPTURE_CFG          1037
#define IDC_BTN_ACTIVATE_CARD           1038
#define IDC_STATIC_FACEDETECT_CFG       1038
#define IDC_BTN_M1_PWD_VERIFY           1039
#define IDC_STATIC_VIDEO1_TYPE          1039
#define IDC_BTN_READ_BLOCK              1040
#define IDC_BTN_WRITE_BLOCK             1041
#define IDC_STATIC_AUDIO1_TYPE          1041
#define IDC_BTN_MOD_BLOCK               1042
#define IDC_COM_BEEP_TYPE               1043
#define IDC_STATIC_DEV1_CFG             1043
#define IDC_EDT_BEEP_COUNT              1044
#define IDC_COM_FLICKER_TYPE            1045
#define IDC_EDT_FLICKER_COUNT           1046
#define IDC_BTN_CFG                     1047
#define IDC_EDT_USER_NAME               1049
#define IDC_STATIC_CAPTURE_CFG2         1049
#define IDC_EDT_PWD                     1050
#define IDC_STATIC_CAPTURE_STREAM_TYPE2 1050
#define IDC_STA_DEV_NAME                1051
#define IDC_COM_STREAM_TYPE             1051
#define IDC_STA_SERIAL_NUMBER           1052
#define IDC_CHK_CAPTURE_AUDIO3          1052
#define IDC_STA_HAIRPIN_VER             1053
#define IDC_BTN_GET                     1054
#define IDC_COM_FACEDETECT_TYPE         1054
#define IDC_BTN_SET                     1055
#define IDC_STA_SERIAL_NO               1055
#define IDC_STA_RET_LEN                 1056
#define IDC_STA_SOFTWARE_VER            1056
#define IDC_STA_RET_DATA                1057
#define IDC_BTN_REG                     1058
#define IDC_BTN_SET_DEV_KEY             1059
#define IDC_EDT_DEV_KEY                 1060
#define IDC_BTN_SET_KEY                 1061
#define IDC_COM_CARD_PROTO              1063
#define IDC_EDT_WAIT_SECOND             1065
#define IDC_BTN_ACTIVATE                1066
#define IDC_STA_SERIAL_LEN              1067
#define IDC_STA_SERIAL                  1068
#define IDC_STA_SEL_VERIFY_LEN          1069
#define IDC_COM_PWD_TYPE                1069
#define IDC_STA_SEL_VERIFY              1070
#define IDC_EDT_SECTION_NUM             1070
#define IDC_STA_CARD_PROTO              1071
#define IDC_BTN_VERIFY                  1072
#define IDC_BTN_ACTIVATE2               1072
#define IDC_EDT_BLOCK_ADDR              1073
#define IDC_BTN_STOP_ACTIVATE           1073
#define IDC_EDT_BLOCK_DATA              1075
#define IDC_BTN_READ                    1076
#define IDC_BTN_WRITE                   1077
#define IDC_EDT_PWD_A                   1079
#define IDC_EDT_CTRL_BYTES              1080
#define IDC_EDT_PWD_B                   1081
#define IDC_BTN_MODIFY                  1082
#define IDC_EDT_VALUE                   1084
#define IDC_BTN_OK                      1085
#define IDC_BTN_STOP                    1088
#define IDC_COM_SOCKET                  1089
#define IDC_COM_CARD_TYPE               1091
#define IDC_COM_CARD_PROTO_TYPE         1092
#define IDC_EDT_DELAY                   1093
#define IDC_BTN_RESET                   1095
#define IDC_STA_DATA_LEN                1097
#define IDC_EDT_DATA                    1098
#define IDC_BTN_SET_USER_DATA           1099
#define IDC_EDT_DATA_LEN                1106
#define IDC_COM_KEY_LEN                 1108
#define IDC_STA_SDK_VER                 1109
#define IDC_STA_SDK_BUILDER_VER         1110
#define IDC_EDT_PASSWORD                1112
#define IDC_BTN_UPGRADE                 1113
#define IDC_EDT_FILE_PATH               1114
#define IDC_BTN_SELECT                  1115
#define IDC_STA_UPGRADE_STATE           1117
#define IDC_PROGRESS_SUB                1119
#define IDC_PROGRESS_TOTAL              1120
#define IDC_STA_SUB_PROGRESS            1121
#define IDC_STA_TOTAL_PROGRESS          1122
#define IDC_LST_LOG                     1122
#define IDC_RAD_BINARY                  1123
#define IDC_RAD_TEXT                    1124
#define IDC_RAD_HEX                     1127
#define IDC_EDT_TIMEOUT                 1128
#define IDC_BTN_GET_CERTIFICATE_INFO    1129
#define IDC_BTN_GET_CERTIFICATE_ADD_ADDR_INFO 1130
#define IDC_BTN_GET_CERTIFICATE_MAC     1131
#define IDC_BTN_GET_IC_CARD_NO          1132
#define IDC_EDIT_WORD_INFO              1133
#define IDC_BTN_DETECT_CARD             1133
#define IDC_EDIT_PIC_INFO               1134
#define IDC_EDIT_ADD_ADDR_INFO          1134
#define IDC_BTN_GET_EXTERNAL_DEV_INFO   1134
#define IDC_EDIT_FINGER_PRINT_INFO      1135
#define IDC_EDIT_CERTIFICATE_MAC        1135
#define IDC_BTN_FINGER_CFG              1135
#define IDC_EDIT_IC_CARD_NO             1136
#define IDC_BTN_STATE_SECRET_PUBLISH    1136
#define IDC_BTN_DETECT                  1137
#define IDC_BTN_ISAPI_TRANSCONFIG       1137
#define IDC_EDIT_WAIT_SECOND            1138
#define IDC_BTN_ONLINECOLLECTION        1138
#define IDC_EDIT_WAIT_SECOND2           1139
#define IDC_COM_CERTIFICATE_TYPE        1139
#define IDC_BTN_STATUS_GET              1139
#define IDC_BTN_OFFLINECOLLECTION2      1139
#define IDC_BTN_CPU_CARD_ENCRYPT_CFG    1140
#define IDC_BTN_CPU_CARD_EN             1140
#define IDC_EDIT_MODULE_VERSION         1141
#define IDC_EDIT_LEADER_FACTOR1         1141
#define IDC_EDIT_MODULE_SERIAL          1142
#define IDC_COMBO_COMPARE_RS            1142
#define IDC_EDIT_LEADER_FACTOR2         1142
#define IDC_EDIT_SECURITY_SERIAL        1143
#define IDC_EDIT_FP_QUALITY             1143
#define IDC_EDIT_LEADER_FACTOR3         1143
#define IDC_COMBO_PRINT_OPER            1144
#define IDC_BTN_TRIGGER_GENERATE_ROOT_KEY 1144
#define IDC_EDIT_KEY_LENGTH             1144
#define IDC_COMBO_CAPTURE_TYPE          1145
#define IDC_EDIT_KEY                    1145
#define IDC_EDIT_TIMEOUT                1146
#define IDC_BTN_TRIGGER_GENERATE_KEY_MEMORY_CARD 1146
#define IDC_STATIC_1                    1146
#define IDC_STATIC_KEY_LENGTH           1146
#define IDC_COMBO_MATCH_LEVEL           1147
#define IDC_BTN_TRIGGER_RECOVER_KEY     1147
#define IDC_STATIC_2                    1147
#define IDC_STATIC_KEY                  1147
#define IDC_EDIT_PRODUCE_NUMBER         1148
#define IDC_BTN_M1_SECTION_ENCRYPT      1148
#define IDC_EDIT_PUBLISH_NUMBER         1149
#define IDC_EDIT_WAIT                   1150
#define IDC_BTN_SEND                    1150
#define IDC_COMBO_FPTYPE                1151
#define IDC_BTN_MAKE_WORK_PSAM_CARD     1151
#define IDC_EDIT_SECTIONID              1151
#define IDC_COMBO_RESULT                1152
#define IDC_EDIT_PRODUCE_NUMBER2        1152
#define IDC_COMBO_KEYTYPE               1152
#define IDC_EDIT_FRINT_INFO             1153
#define IDC_EDIT_PUBLISH_NUMBER2        1153
#define IDC_EDIT2                       1153
#define IDC_EDIT_FP_TEMP_QUALITY        1154
#define IDC_EDIT_JOB_NUMBER2            1154
#define IDC_EDIT3                       1154
#define IDC_BTN_CAPTURE                 1155
#define IDC_BTN_MAKE_WASH_PSAM_KEY_CARD 1155
#define IDC_COMBO2                      1155
#define IDC_EDIT_ENNAME                 1155
#define IDC_EDIT12                      1155
#define IDC_EDIT_FILE_NO                1156
#define IDC_EDIT4                       1156
#define IDC_BTN_TRIGGER_WASH_CARD       1157
#define IDC_EDIT5                       1157
#define IDC_EDIT_SUB_DIR_NO             1158
#define IDC_EDIT_ADDR                   1158
#define IDC_EDIT_CFGINPUT               1158
#define IDC_EDIT13                      1158
#define IDC_EDIT_SUB_DIR_NO2            1159
#define IDC_EDIT_CFGOUTPUT              1159
#define IDC_EDIT14                      1159
#define IDC_EDIT_CARD_CONTENT_PATH      1160
#define IDC_EDIT_ID                     1160
#define IDC_COMBO_REQUEST_TYPE          1160
#define IDC_EDIT15                      1160
#define IDC_EDIT_JOB_NUMBER3            1161
#define IDC_EDIT_ISSUAUTH               1161
#define IDC_EDIT_COMMAND                1161
#define IDC_BTN_TRIGGER_CHANGE_KEY      1162
#define IDC_EDIT_STARTDATE              1162
#define IDC_BUTTON_OPERATION            1162
#define IDC_BTN_READ_CARD_PUBLIC_INFO   1163
#define IDC_EDIT_ENDDATE                1163
#define IDC_BUTTON_EXIT                 1163
#define IDC_BTN_READ_CARD_SUB_DIR_INFO  1164
#define IDC_EDIT_NAME                   1164
#define IDC_CHECK1                      1164
#define IDC_BTN_WRITE_CPU_CARD_USER_INFO 1165
#define IDC_EDIT_NATION                 1165
#define IDC_EDIT1                       1165
#define IDC_EDIT_MODULEID               1165
#define IDC_CHK_SEPARATE                1165
#define IDC_EDIT_HEALTH_CODE_SERVER_ADDRESS 1165
#define IDC_EDIT_UPLOAD_FILE_PATH       1165
#define IDC_EDIT_CARD_CONTENT_SIZE      1166
#define IDC_RADIO_LENAUTOOPEN           1166
#define IDC_COMBO_MIME_TYPE             1166
#define IDC_EDIT11                      1166
#define IDC_EDIT_UPLOAD_REMOTE_FILE_PATH 1166
#define IDC_EDIT_CUR_STATUS             1167
#define IDC_RADIO_LENAUTOCLOSE          1167
#define IDC_COMBO1                      1167
#define IDC_EDIT_DOWNLOAD_FILE_PATH     1167
#define IDC_EDIT_SFI                    1168
#define IDC_EDIT_PASSNO                 1168
#define IDC_BTN_START_PREVIEW           1168
#define IDC_EDIT_ADF_NAME               1169
#define IDC_COMBO_CARDNOLEN             1169
#define IDC_BTN_STOP_PREVIEW            1169
#define IDC_EDIT_DOWNLOAD_REMOTE_FILE_PATH 1169
#define IDC_EDIT_JOB_NUMBER4            1170
#define IDC_EDIT_CARDNO                 1170
#define IDC_BTN_START_RECORD            1170
#define IDC_SLIDER1                     1170
#define IDC_EDIT_JOB_NUMBER_NEW         1171
#define IDC_EDIT_ISSUNUM                1171
#define IDC_BTN_STOP_RECORD             1171
#define IDC_SLIDER2                     1171
#define IDC_EDIT_CUSTOM_CARD_NO         1172
#define IDC_EDIT_CERTITYPE              1172
#define IDC_BTN_START_FACEDETECT        1172
#define IDC_BUTTON_GET_VIDEO_CAP        1172
#define IDC_BTN_PUBLISH_OPERATE         1173
#define IDC_BUTTON_CAPTURECARD          1173
#define IDC_BTN_STOP_FACEDETECT         1173
#define IDC_BUTTON_SET_DEFAULT_CAP      1173
#define IDC_EDIT_SUB_DIR                1174
#define IDC_EDIT_CARDTYPE               1174
#define IDC_BTN_START_STREAMCALLBACK    1174
#define IDC_SLIDER3                     1174
#define IDC_BTN_TRIGGER_CARD_PUBLISH    1175
#define IDC_EDIT_PRCN                   1175
#define IDC_BTN_STOP_STREAMCALLBACK     1175
#define IDC_SLIDER4                     1175
#define IDC_EDIT_ADF_NAME2              1176
#define IDC_EDIT_NOACODE                1176
#define IDC_SLIDER5                     1176
#define IDC_EDIT_ADF_SIZE               1177
#define IDC_EDIT_VERSION                1177
#define IDC_SLIDER6                     1177
#define IDC_EDIT_ADF_KEY_VALUE          1178
#define IDC_EDIT_RACODE                 1178
#define IDC_EDIT6                       1178
#define IDC_BTN_SAVE                    1179
#define IDC_EDIT_PRINTINFO              1179
#define IDC_SLIDER7                     1179
#define IDC_EDIT_PIC                    1180
#define IDC_EDIT7                       1180
#define IDC_EDIT_CHNAME                 1181
#define IDC_SLIDER8                     1181
#define IDC_EDIT_SEX                    1182
#define IDC_EDIT8                       1182
#define IDC_EDIT_BIRTH                  1183
#define IDC_SLIDER9                     1183
#define IDC_BUTTON_CAPTUREIDINFO        1184
#define IDC_EDIT9                       1184
#define IDC_COMBO_CAPTUREINF            1185
#define IDC_SLIDER10                    1185
#define IDC_COMBO_DATATYPE              1186
#define IDC_EDIT10                      1186
#define IDC_STATIC1                     1187
#define IDC_EDIT_FACEDATA               1188
#define IDC_STATIC2                     1188
#define IDC_EDIT_INFRAREDFACEDATA       1189
#define IDC_STATIC3                     1189
#define IDC_BUTTON_CAPTUREFACE          1190
#define IDC_STATIC4                     1190
#define IDC_PROGRESS_CAPTUREPROGRESS    1191
#define IDC_STATIC5                     1191
#define IDC_BUTTON_IDDATAPATH           1192
#define IDC_STATIC6                     1192
#define IDC_BUTTON_FACEDATA             1193
#define IDC_STATIC7                     1193
#define IDC_BUTTON_CAPTUREFINGER        1194
#define IDC_STATIC8                     1194
#define IDC_BUTTON_FINGERDATA           1195
#define IDC_STATIC9                     1195
#define IDC_STATIC10                    1196
#define IDC_SLIDER11                    1197
#define IDC_STATIC11                    1198
#define IDC_CHECK_FINGER1               1199
#define IDC_SLIDER12                    1199
#define IDC_CHECK_FINGER2               1200
#define IDC_STATIC12                    1200
#define IDC_CHECK_FINGER3               1201
#define IDC_SLIDER13                    1201
#define IDC_CHECK_FINGER4               1202
#define IDC_STATIC13                    1202
#define IDC_CHECK_FINGER5               1203
#define IDC_SLIDER14                    1203
#define IDC_CHECK_FINGER6               1204
#define IDC_STATIC14                    1204
#define IDC_CHECK_FINGER7               1205
#define IDC_SLIDER15                    1205
#define IDC_CHECK_FINGER8               1206
#define IDC_STATIC15                    1206
#define IDC_CHECK_FINGER9               1207
#define IDC_SLIDER16                    1207
#define IDC_CHECK_FINGER10              1208
#define IDC_STATIC16                    1208
#define IDC_EDITFPRESULT1               1209
#define IDC_EDIT16                      1209
#define IDC_EDITFPRESULT2               1210
#define IDC_SLIDER17                    1210
#define IDC_EDITFPRESULT3               1211
#define IDC_STATIC17                    1211
#define IDC_EDITFPRESULT4               1212
#define IDC_EDIT17                      1212
#define IDC_EDITFPRESULT5               1213
#define IDC_BT_START_PREVIEW            1213
#define IDC_EDITFPRESULT6               1214
#define IDC_BT_STOP_PREVIEW2            1214
#define IDC_BT_STOP_PREVIEW             1214
#define IDC_CHK_INCLUDE_ALL             1214
#define IDC_EDITFPRESULT7               1215
#define IDC_COMBO_COMMAND               1215
#define IDC_EDITFPRESULT8               1216
#define IDC_COMBO_DECODE_TYPE           1216
#define IDC_EDITFPRESULT9               1217
#define IDC_EDIT18                      1217
#define ID_LANGUAGE_OK                  1217
#define IDC_EDITFPRESULT10              1218
#define IDC_STATIC19                    1218
#define IDC_RADIO_CH                    1218
#define IDC_CHECK_ALLFINGERS            1219
#define IDC_RADIO_EN                    1219
#define IDC_BUTTON_PRESET               1220
#define IDC_STATIC_V1                   1220
#define IDC_STATIC_SDKV                 1221
#define IDC_STATIC_USERINFO             1222
#define IDC_STATIC_USER_NAME            1223
#define IDC_STATIC_PW                   1224
#define IDC_STATIC_DEVICE_NAME          1225
#define IDC_STATIC20                    1226
#define IDC_STATIC_DEVICE_INFO          1226
#define IDC_STATIC_DEVICE_SERIAL        1227
#define IDC_STATIC_BEEP_TYPE            1228
#define IDC_BUTTON_INFOFILETEMPLATE     1229
#define IDC_STATIC_FILCKER_TYPE         1229
#define IDC_COMBO_NAMECHECK             1230
#define IDC_STATIC_BEEP_COUNT           1230
#define IDC_COMBO_NAME                  1231
#define IDC_STATIC_FLICKER_COUNT        1231
#define IDC_COMBO_EMPNO                 1232
#define IDC_STATIC_CARD_DEVICE_NAME     1232
#define IDC_COMBO_IDNUM                 1233
#define IDC_STATIC_CARD_DEVICE_SERIVAL  1233
#define IDC_COMBO_IDSER                 1234
#define IDC_STATIC_SOFTWARE_VERSION     1234
#define IDC_COMBO_DETAIL                1235
#define IDC_STATIC_TEXT                 1235
#define IDC_COMBO_CARD                  1236
#define IDC_STATIC_TIME                 1236
#define IDC_COMBO_CARD_IDENTITY         1237
#define IDC_COMBO_FACE                  1237
#define IDC_STATIC_SECOND               1237
#define IDC_COMBO_CARD_TYPE             1238
#define IDC_STATIC_MODEL_ID             1238
#define IDC_COMBO_CARD_TYPE2            1239
#define IDC_STATIC_PATH                 1239
#define IDC_COMBO_CUSTOM_CARD_ENABLE    1240
#define IDC_STATIC_STATUS               1240
#define IDC_COMBO_CRYPT_TYPE2           1241
#define IDC_STATIC_PROG                 1241
#define IDC_COMBO_CARD_TYPE3            1242
#define IDC_STATIC_DATA_LEN             1242
#define IDC_COMBO_OPERATE               1243
#define IDC_STATIC_DATA                 1243
#define IDC_COMBO_SUB_DIR_NO            1244
#define IDC_STATIC_KEY_LEN              1244
#define IDC_COMBO_ADF_KEY_MODE          1245
#define IDC_STATIC_TYPE                 1245
#define IDC_COMBO_CARD_SLOT_TYPE        1246
#define IDC_EDIT_LENNAME                1246
#define IDC_STATIC_WAIT_TIME            1246
#define IDC_EDIT_LENEMP                 1247
#define IDC_STATIC_SEC                  1247
#define IDC_COMBO_CARD_SLOT_TYPE2       1248
#define IDC_EDIT_LENID                  1248
#define IDC_STATIC_RSP                  1248
#define IDC_COMBO_CARD_SLOT_TYPE3       1249
#define IDC_EDIT_LENSER                 1249
#define IDC_STATIC_PRO_TYPE             1249
#define IDC_COMBO_CRYPT_TYPE            1250
#define IDC_EDIT_LENDET                 1250
#define IDC_STATIC_SER_LEN              1250
#define IDC_EDIT_LENCARD                1251
#define IDC_STATIC_SERIAL               1251
#define IDC_COMBO_CARD_SLOT_TYPE4       1252
#define IDC_EDIT_LENFACE                1252
#define IDC_STATIC_SELECT_LEN           1252
#define IDC_BUTTON_RULECFG              1253
#define IDC_STATIC_SELECT               1253
#define IDC_STATIC_PWD_TYPE             1254
#define IDC_STATIC_BLOCK_ID             1255
#define IDC_STATIC_PWD                  1256
#define IDC_STATIC_BLOCK_ADDRESS        1257
#define IDC_STATIC_BLOCK_DATA           1258
#define IDC_STATIC_BLOCK_NO             1259
#define IDC_STATIC_PWDA                 1260
#define IDC_STATIC_CONTROL              1261
#define IDC_EDIT_NUMNAME                1262
#define IDC_STATIC_PWDB                 1262
#define IDC_EDIT_NUMID                  1263
#define IDC_STATIC_ADDRESS              1263
#define IDC_EDIT_NUMIDEN                1264
#define IDC_STATIC_TIMEOUT              1264
#define IDC_EDIT_NUMSER                 1265
#define IDC_STATIC_BLOCKID              1265
#define IDC_EDIT_NUMDET                 1266
#define IDC_STATIC_ENCRYPT              1266
#define IDC_EDIT_NUMCARD                1267
#define IDC_STATIC_                     1267
#define IDC_STATIC_VERIFY_PWD           1267
#define IDC_EDIT_NUMFACE                1268
#define IDC_STATIC_NEW_PWD              1268
#define IDC_STATIC_KEY1                 1269
#define IDC_EDIT_UNQEMP                 1270
#define IDC_STATIC200                   1270
#define IDC_STATIC300                   1271
#define IDC_EDIT_UNQID                  1272
#define IDC_STATIC400                   1272
#define IDC_STATIC500                   1273
#define IDC_EDIT_UNQSER                 1274
#define IDC_STATIC600                   1274
#define IDC_EDIT_UNQDET                 1275
#define IDC_STATIC700                   1275
#define IDC_EDIT_UNQCARD                1276
#define IDC_STATIC800                   1276
#define IDC_EDIT_UNQFACE                1277
#define IDC_STATIC900                   1277
#define IDC_STATIC1000                  1278
#define IDC_STATIC1100                  1279
#define IDC_STATIC1200                  1280
#define IDC_STATIC1300                  1281
#define IDC_STATIC1400                  1282
#define IDC_STATIC1500                  1283
#define IDC_STATIC1600                  1284
#define IDC_STATIC1700                  1285
#define IDC_EDITFPRESULT11              1286
#define IDC_EDITFPRESULT12              1287
#define IDC_EDITFPRESULT13              1288
#define IDC_EDITFPRESULT14              1289
#define IDC_EDITFPRESULT15              1290
#define IDC_EDITFPRESULT16              1291
#define IDC_EDITFPRESULT17              1292
#define IDC_EDITFPRESULT18              1293
#define IDC_EDITFPRESULT19              1294
#define IDC_EDITFPRESULT20              1295
#define IDC_STATIC1800                  1296
#define IDC_STATIC1900                  1297
#define IDC_STATIC2000                  1298
#define IDC_STATIC2100                  1299
#define IDC_STATIC2200                  1300
#define IDC_STATIC2300                  1301
#define IDC_STATIC2400                  1302
#define IDC_STATIC2500                  1303
#define IDC_STATIC2600                  1304
#define IDC_STATIC2700                  1305
#define IDC_STATIC2800                  1306
#define IDC_STATIC2900                  1307
#define IDC_STATIC3000                  1308
#define IDC_STATIC3100                  1309
#define IDC_STATIC3200                  1310
#define IDC_STATIC3300                  1311
#define IDC_STATIC3400                  1312
#define IDC_STATIC3500                  1313
#define IDC_STATIC3600                  1314
#define IDC_STATIC3700                  1315
#define IDC_STATIC3800                  1316
#define IDC_STATIC3900                  1317
#define IDC_STATIC4000                  1318
#define IDC_STATIC4100                  1319
#define IDC_STATIC120                   1320
#define IDC_STATIC130                   1321
#define IDC_STATIC140                   1322
#define IDC_STATIC150                   1323
#define IDC_STATIC160                   1324
#define IDC_STATIC170                   1325
#define IDC_BUTTON1                     1326
#define IDC_CHECK2                      1327
#define IDC_BTN_HEALTH_CODE             1327
#define IDC_RADIO_ENCRYPT               1327
#define IDC_STATIC_HEALTH_CODE_CFG      1328
#define IDC_RADIO_UPLOAD                1328
#define IDC_STATIC_SERVER_ADDRESS       1329
#define IDC_RADIO_DOWNLOAD              1329
#define IDC_BTN_GET_HEALTH_CODE_CFG     1330
#define IDC_EDIT_ENCRYPT_FILE_PATH      1330
#define IDC_BTN_SET_HEALTH_CODE_CFG     1331
#define IDC_BTN_SELECT_ENCRYPT_FILE     1331
#define IDC_CHECK_HEALTH_CODE_ENABLE    1332
#define IDC_BTN_FILE_TRANSFER_START     1332
#define IDC_STATIC_SEARCH_HEALTH_CODE   1333
#define IDC_BTN_SELECT_UPLOAD_FILE      1333
#define IDC_STATIC_QUERY_UUID           1334
#define IDC_EDIT_QUERY_UUID             1335
#define IDC_EDIT_HEALTH_CODE            1336
#define IDC_BTN_GET_HEALTH_CODE         1337
#define IDC_STATIC_HEALTH_CODE_RESULT   1338
#define IDC_EDIT_HEALTH_CODE_RESULT     1339
#define IDC_BTN_SET_HEALTH_CODE_RESULT  1340
#define IDC_STATIC_EZVIZ_STU            1341
#define IDC_STATIC_EZVIZ_STATE          1341
#define IDC_DATE_CURRENT                1780
#define IDC_TIME_CURRENT                1781
#define IDC_DATE_END                    1784
#define IDC_TIME_END                    1785
#define IDC_BTN_SELECT_FILE             1999

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        190
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1342
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
