/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.2.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFormLayout>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QTabWidget *tabWidget;
    QWidget *tab;
    QFrame *robotframe9;
    QPushButton *pushButton_33;
    QPushButton *pushButton_34;
    QLabel *axisposition9;
    QLabel *axisname9;
    QPushButton *CalibrateC_R2;
    QLabel *phoframe3;
    QFrame *frame_12;
    QPushButton *pushButton_7;
    QPushButton *pushButton_8;
    QLabel *label_7;
    QLabel *label_8;
    QFrame *frame_37;
    QPushButton *pushButton_13;
    QPushButton *pushButton_14;
    QLabel *label_13;
    QLabel *label_14;
    QFrame *frame_38;
    QPushButton *pushButton_15;
    QPushButton *pushButton_16;
    QLabel *label_15;
    QLabel *label_16;
    QFrame *frame_39;
    QPushButton *pushButton_17;
    QPushButton *pushButton_18;
    QLabel *label_17;
    QLabel *label_18;
    QFrame *frame_40;
    QPushButton *pushButton_19;
    QPushButton *pushButton_20;
    QLabel *label_19;
    QLabel *label_20;
    QFrame *frame_41;
    QPushButton *pushButton_21;
    QPushButton *pushButton_22;
    QLabel *label_21;
    QLabel *label_22;
    QFrame *robotframe4;
    QPushButton *pushButton_23;
    QPushButton *pushButton_24;
    QLabel *axisposition4;
    QLabel *axisname4;
    QWidget *layoutWidget_3;
    QHBoxLayout *horizontalLayout;
    QPushButton *robotswitch;
    QLabel *label_37;
    QFrame *robotframe3;
    QPushButton *pushButton_5;
    QPushButton *pushButton_6;
    QLabel *axisposition3;
    QLabel *axisname3;
    QFrame *robotframe7;
    QPushButton *pushButton_35;
    QPushButton *pushButton_36;
    QLabel *axisposition7;
    QLabel *axisname7;
    QPushButton *matlabtest;
    QFrame *frame_36;
    QLineEdit *lineEdit_13;
    QLineEdit *lineEdit_14;
    QLineEdit *lineEdit_15;
    QLineEdit *lineEdit_16;
    QLineEdit *lineEdit_17;
    QLineEdit *lineEdit_18;
    QLineEdit *lineEdit_19;
    QLineEdit *lineEdit_20;
    QLineEdit *lineEdit_21;
    QLineEdit *lineEdit_22;
    QLineEdit *lineEdit_23;
    QLineEdit *lineEdit_24;
    QLineEdit *lineEdit_25;
    QLineEdit *lineEdit_26;
    QLineEdit *lineEdit_27;
    QLineEdit *lineEdit_28;
    QLabel *label_59;
    QPushButton *robotikine1;
    QPushButton *robotikine2;
    QFrame *robotframe12;
    QPushButton *pushButton_29;
    QPushButton *pushButton_30;
    QLabel *axisposition12;
    QLabel *axisname12;
    QFrame *frame_29;
    QLabel *label_44;
    QLabel *label_45;
    QLabel *label_46;
    QLabel *label_47;
    QLabel *label_48;
    QFrame *line_2;
    QLabel *label_49;
    QLabel *label_50;
    QLabel *label_51;
    QLabel *label_52;
    QLabel *label_53;
    QLabel *label_54;
    QLabel *label_55;
    QLabel *label_56;
    QLabel *label_57;
    QFrame *line_3;
    QPushButton *show2D;
    QPushButton *calculate3D;
    QPushButton *checkaccuracy;
    QPushButton *Robot_move;
    QFrame *frame_34;
    QLineEdit *lineEdit;
    QLineEdit *lineEdit_2;
    QLineEdit *lineEdit_3;
    QLineEdit *lineEdit_4;
    QLineEdit *lineEdit_5;
    QLineEdit *lineEdit_6;
    QLineEdit *lineEdit_7;
    QLineEdit *lineEdit_8;
    QLineEdit *lineEdit_9;
    QLineEdit *lineEdit_10;
    QLineEdit *lineEdit_11;
    QLineEdit *lineEdit_12;
    QPushButton *robotkine1;
    QPushButton *robotkine2;
    QLabel *label_58;
    QPushButton *test_new_robot;
    QFrame *robotframe10;
    QPushButton *pushButton_25;
    QPushButton *pushButton_26;
    QLabel *axisposition10;
    QLabel *axisname10;
    QWidget *layoutWidget_4;
    QHBoxLayout *horizontalLayout_2;
    QPushButton *cameraswitch;
    QLabel *label_43;
    QFrame *robotframe2;
    QPushButton *pushButton_3;
    QPushButton *pushButton_4;
    QLabel *axisposition2;
    QLabel *axisname2;
    QFrame *line_5;
    QPushButton *getposition;
    QFrame *robotframe11;
    QPushButton *pushButton_31;
    QPushButton *pushButton_32;
    QLabel *axisposition11;
    QLabel *axisname11;
    QPushButton *stop_button;
    QFrame *robotframe1;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QLabel *axisposition1;
    QLabel *axisname1;
    QFrame *robotframe8;
    QPushButton *pushButton_27;
    QPushButton *pushButton_28;
    QLabel *axisposition8;
    QLabel *axisname8;
    QFrame *robotframe6;
    QPushButton *pushButton_11;
    QPushButton *pushButton_12;
    QLabel *axisposition6;
    QLabel *axisname6;
    QLabel *phoframe1;
    QPushButton *showtool;
    QFrame *robotframe5;
    QPushButton *pushButton_9;
    QPushButton *pushButton_10;
    QLabel *axisposition5;
    QLabel *axisname5;
    QLabel *phoframe2;
    QPushButton *pushButton_49;
    QPushButton *showpic;
    QComboBox *Robot_select;
    QPushButton *pushButton_43;
    QPushButton *pushButton_44;
    QPushButton *pushButton_45;
    QPushButton *pushButton_46;
    QPushButton *pushButton_47;
    QPushButton *pushButton_48;
    QPushButton *pushButton_50;
    QPushButton *pushButton_51;
    QPushButton *pushButton_52;
    QPushButton *pushButton_53;
    QPushButton *pushButton_54;
    QPushButton *pushButton_55;
    QPushButton *pushButton_56;
    QPushButton *pushButton_57;
    QPushButton *pushButton_58;
    QWidget *tab_2;
    QFrame *frame;
    QWidget *layoutWidget;
    QHBoxLayout *horizontalLayout_3;
    QVBoxLayout *verticalLayout_2;
    QLabel *label;
    QLabel *label_3;
    QVBoxLayout *verticalLayout;
    QComboBox *comboBox;
    QComboBox *comboBox_2;
    QWidget *layoutWidget1;
    QVBoxLayout *verticalLayout_3;
    QPushButton *port_turnon;
    QPushButton *pushButton_40;
    QLabel *label_2;
    QWidget *layoutWidget2;
    QHBoxLayout *horizontalLayout_4;
    QLineEdit *telegram_Edit;
    QPushButton *sent_telegram;
    QTextEdit *readport_text;
    QFrame *frame_2;
    QFormLayout *formLayout;
    QLabel *label_4;
    QLabel *label_5;
    QSlider *horizontalSlider_2;
    QSlider *horizontalSlider_1;
    QLabel *label_6;
    QLabel *miniCamera_label1;
    QLabel *miniCamera_label2;
    QPushButton *pushButton_38;
    QPushButton *pushButton_39;
    QPushButton *pushButton_41;
    QPushButton *pushButton_42;
    QPushButton *stop_button_2;
    QPushButton *pushButton_37;
    QWidget *tab_3;
    QPushButton *Model_predict;
    QPushButton *Py_initialize;
    QLabel *predict_pic1;
    QLabel *predict_pic2;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1400, 900);
        MainWindow->setStyleSheet(QString::fromUtf8("background-color: rgb(240, 240, 240);"));
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        tabWidget = new QTabWidget(centralwidget);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(-2, -3, 1400, 870));
        tabWidget->setStyleSheet(QString::fromUtf8("background-color: rgb(240, 240, 240);"));
        tabWidget->setMovable(false);
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        robotframe9 = new QFrame(tab);
        robotframe9->setObjectName(QString::fromUtf8("robotframe9"));
        robotframe9->setEnabled(true);
        robotframe9->setGeometry(QRect(420, 150, 191, 111));
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(robotframe9->sizePolicy().hasHeightForWidth());
        robotframe9->setSizePolicy(sizePolicy);
        robotframe9->setFrameShape(QFrame::WinPanel);
        robotframe9->setFrameShadow(QFrame::Sunken);
        pushButton_33 = new QPushButton(robotframe9);
        pushButton_33->setObjectName(QString::fromUtf8("pushButton_33"));
        pushButton_33->setGeometry(QRect(10, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_33->sizePolicy().hasHeightForWidth());
        pushButton_33->setSizePolicy(sizePolicy);
        pushButton_34 = new QPushButton(robotframe9);
        pushButton_34->setObjectName(QString::fromUtf8("pushButton_34"));
        pushButton_34->setGeometry(QRect(100, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_34->sizePolicy().hasHeightForWidth());
        pushButton_34->setSizePolicy(sizePolicy);
        axisposition9 = new QLabel(robotframe9);
        axisposition9->setObjectName(QString::fromUtf8("axisposition9"));
        axisposition9->setEnabled(true);
        axisposition9->setGeometry(QRect(80, 10, 101, 41));
        sizePolicy.setHeightForWidth(axisposition9->sizePolicy().hasHeightForWidth());
        axisposition9->setSizePolicy(sizePolicy);
        axisposition9->setFrameShape(QFrame::WinPanel);
        axisposition9->setFrameShadow(QFrame::Plain);
        axisname9 = new QLabel(robotframe9);
        axisname9->setObjectName(QString::fromUtf8("axisname9"));
        axisname9->setGeometry(QRect(10, 20, 52, 18));
        sizePolicy.setHeightForWidth(axisname9->sizePolicy().hasHeightForWidth());
        axisname9->setSizePolicy(sizePolicy);
        axisname9->setFrameShape(QFrame::Box);
        CalibrateC_R2 = new QPushButton(tab);
        CalibrateC_R2->setObjectName(QString::fromUtf8("CalibrateC_R2"));
        CalibrateC_R2->setGeometry(QRect(900, 730, 80, 31));
        phoframe3 = new QLabel(tab);
        phoframe3->setObjectName(QString::fromUtf8("phoframe3"));
        phoframe3->setGeometry(QRect(980, 290, 260, 260));
        phoframe3->setFrameShape(QFrame::Box);
        phoframe3->setLineWidth(2);
        frame_12 = new QFrame(tab);
        frame_12->setObjectName(QString::fromUtf8("frame_12"));
        frame_12->setEnabled(true);
        frame_12->setGeometry(QRect(620, 10, 191, 111));
        sizePolicy.setHeightForWidth(frame_12->sizePolicy().hasHeightForWidth());
        frame_12->setSizePolicy(sizePolicy);
        frame_12->setFrameShape(QFrame::WinPanel);
        frame_12->setFrameShadow(QFrame::Sunken);
        pushButton_7 = new QPushButton(frame_12);
        pushButton_7->setObjectName(QString::fromUtf8("pushButton_7"));
        pushButton_7->setGeometry(QRect(10, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_7->sizePolicy().hasHeightForWidth());
        pushButton_7->setSizePolicy(sizePolicy);
        pushButton_8 = new QPushButton(frame_12);
        pushButton_8->setObjectName(QString::fromUtf8("pushButton_8"));
        pushButton_8->setGeometry(QRect(100, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_8->sizePolicy().hasHeightForWidth());
        pushButton_8->setSizePolicy(sizePolicy);
        label_7 = new QLabel(frame_12);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setEnabled(true);
        label_7->setGeometry(QRect(80, 10, 101, 41));
        sizePolicy.setHeightForWidth(label_7->sizePolicy().hasHeightForWidth());
        label_7->setSizePolicy(sizePolicy);
        label_7->setFrameShape(QFrame::WinPanel);
        label_7->setFrameShadow(QFrame::Plain);
        label_8 = new QLabel(frame_12);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(10, 20, 52, 18));
        sizePolicy.setHeightForWidth(label_8->sizePolicy().hasHeightForWidth());
        label_8->setSizePolicy(sizePolicy);
        label_8->setFrameShape(QFrame::Box);
        frame_37 = new QFrame(frame_12);
        frame_37->setObjectName(QString::fromUtf8("frame_37"));
        frame_37->setEnabled(true);
        frame_37->setGeometry(QRect(600, 0, 191, 111));
        sizePolicy.setHeightForWidth(frame_37->sizePolicy().hasHeightForWidth());
        frame_37->setSizePolicy(sizePolicy);
        frame_37->setFrameShape(QFrame::WinPanel);
        frame_37->setFrameShadow(QFrame::Sunken);
        pushButton_13 = new QPushButton(frame_37);
        pushButton_13->setObjectName(QString::fromUtf8("pushButton_13"));
        pushButton_13->setGeometry(QRect(10, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_13->sizePolicy().hasHeightForWidth());
        pushButton_13->setSizePolicy(sizePolicy);
        pushButton_14 = new QPushButton(frame_37);
        pushButton_14->setObjectName(QString::fromUtf8("pushButton_14"));
        pushButton_14->setGeometry(QRect(100, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_14->sizePolicy().hasHeightForWidth());
        pushButton_14->setSizePolicy(sizePolicy);
        label_13 = new QLabel(frame_37);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setEnabled(true);
        label_13->setGeometry(QRect(80, 10, 101, 41));
        sizePolicy.setHeightForWidth(label_13->sizePolicy().hasHeightForWidth());
        label_13->setSizePolicy(sizePolicy);
        label_13->setFrameShape(QFrame::WinPanel);
        label_13->setFrameShadow(QFrame::Plain);
        label_14 = new QLabel(frame_37);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(10, 20, 52, 18));
        sizePolicy.setHeightForWidth(label_14->sizePolicy().hasHeightForWidth());
        label_14->setSizePolicy(sizePolicy);
        label_14->setFrameShape(QFrame::Box);
        frame_38 = new QFrame(frame_12);
        frame_38->setObjectName(QString::fromUtf8("frame_38"));
        frame_38->setEnabled(true);
        frame_38->setGeometry(QRect(200, 0, 191, 111));
        sizePolicy.setHeightForWidth(frame_38->sizePolicy().hasHeightForWidth());
        frame_38->setSizePolicy(sizePolicy);
        frame_38->setFrameShape(QFrame::WinPanel);
        frame_38->setFrameShadow(QFrame::Sunken);
        pushButton_15 = new QPushButton(frame_38);
        pushButton_15->setObjectName(QString::fromUtf8("pushButton_15"));
        pushButton_15->setGeometry(QRect(10, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_15->sizePolicy().hasHeightForWidth());
        pushButton_15->setSizePolicy(sizePolicy);
        pushButton_16 = new QPushButton(frame_38);
        pushButton_16->setObjectName(QString::fromUtf8("pushButton_16"));
        pushButton_16->setGeometry(QRect(100, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_16->sizePolicy().hasHeightForWidth());
        pushButton_16->setSizePolicy(sizePolicy);
        label_15 = new QLabel(frame_38);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setEnabled(true);
        label_15->setGeometry(QRect(80, 10, 101, 41));
        sizePolicy.setHeightForWidth(label_15->sizePolicy().hasHeightForWidth());
        label_15->setSizePolicy(sizePolicy);
        label_15->setFrameShape(QFrame::WinPanel);
        label_15->setFrameShadow(QFrame::Plain);
        label_16 = new QLabel(frame_38);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(10, 20, 52, 18));
        sizePolicy.setHeightForWidth(label_16->sizePolicy().hasHeightForWidth());
        label_16->setSizePolicy(sizePolicy);
        label_16->setFrameShape(QFrame::Box);
        frame_39 = new QFrame(frame_12);
        frame_39->setObjectName(QString::fromUtf8("frame_39"));
        frame_39->setEnabled(true);
        frame_39->setGeometry(QRect(1000, 0, 191, 111));
        sizePolicy.setHeightForWidth(frame_39->sizePolicy().hasHeightForWidth());
        frame_39->setSizePolicy(sizePolicy);
        frame_39->setFrameShape(QFrame::WinPanel);
        frame_39->setFrameShadow(QFrame::Sunken);
        pushButton_17 = new QPushButton(frame_39);
        pushButton_17->setObjectName(QString::fromUtf8("pushButton_17"));
        pushButton_17->setGeometry(QRect(10, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_17->sizePolicy().hasHeightForWidth());
        pushButton_17->setSizePolicy(sizePolicy);
        pushButton_18 = new QPushButton(frame_39);
        pushButton_18->setObjectName(QString::fromUtf8("pushButton_18"));
        pushButton_18->setGeometry(QRect(100, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_18->sizePolicy().hasHeightForWidth());
        pushButton_18->setSizePolicy(sizePolicy);
        label_17 = new QLabel(frame_39);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setEnabled(true);
        label_17->setGeometry(QRect(80, 10, 101, 41));
        sizePolicy.setHeightForWidth(label_17->sizePolicy().hasHeightForWidth());
        label_17->setSizePolicy(sizePolicy);
        label_17->setFrameShape(QFrame::WinPanel);
        label_17->setFrameShadow(QFrame::Plain);
        label_18 = new QLabel(frame_39);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(10, 20, 52, 18));
        sizePolicy.setHeightForWidth(label_18->sizePolicy().hasHeightForWidth());
        label_18->setSizePolicy(sizePolicy);
        label_18->setFrameShape(QFrame::Box);
        frame_40 = new QFrame(frame_12);
        frame_40->setObjectName(QString::fromUtf8("frame_40"));
        frame_40->setEnabled(true);
        frame_40->setGeometry(QRect(800, 0, 191, 111));
        sizePolicy.setHeightForWidth(frame_40->sizePolicy().hasHeightForWidth());
        frame_40->setSizePolicy(sizePolicy);
        frame_40->setFrameShape(QFrame::WinPanel);
        frame_40->setFrameShadow(QFrame::Sunken);
        pushButton_19 = new QPushButton(frame_40);
        pushButton_19->setObjectName(QString::fromUtf8("pushButton_19"));
        pushButton_19->setGeometry(QRect(10, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_19->sizePolicy().hasHeightForWidth());
        pushButton_19->setSizePolicy(sizePolicy);
        pushButton_20 = new QPushButton(frame_40);
        pushButton_20->setObjectName(QString::fromUtf8("pushButton_20"));
        pushButton_20->setGeometry(QRect(100, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_20->sizePolicy().hasHeightForWidth());
        pushButton_20->setSizePolicy(sizePolicy);
        label_19 = new QLabel(frame_40);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setEnabled(true);
        label_19->setGeometry(QRect(80, 10, 101, 41));
        sizePolicy.setHeightForWidth(label_19->sizePolicy().hasHeightForWidth());
        label_19->setSizePolicy(sizePolicy);
        label_19->setFrameShape(QFrame::WinPanel);
        label_19->setFrameShadow(QFrame::Plain);
        label_20 = new QLabel(frame_40);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(10, 20, 52, 18));
        sizePolicy.setHeightForWidth(label_20->sizePolicy().hasHeightForWidth());
        label_20->setSizePolicy(sizePolicy);
        label_20->setFrameShape(QFrame::Box);
        frame_41 = new QFrame(frame_12);
        frame_41->setObjectName(QString::fromUtf8("frame_41"));
        frame_41->setEnabled(true);
        frame_41->setGeometry(QRect(400, 0, 191, 111));
        sizePolicy.setHeightForWidth(frame_41->sizePolicy().hasHeightForWidth());
        frame_41->setSizePolicy(sizePolicy);
        frame_41->setFrameShape(QFrame::WinPanel);
        frame_41->setFrameShadow(QFrame::Sunken);
        pushButton_21 = new QPushButton(frame_41);
        pushButton_21->setObjectName(QString::fromUtf8("pushButton_21"));
        pushButton_21->setGeometry(QRect(10, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_21->sizePolicy().hasHeightForWidth());
        pushButton_21->setSizePolicy(sizePolicy);
        pushButton_22 = new QPushButton(frame_41);
        pushButton_22->setObjectName(QString::fromUtf8("pushButton_22"));
        pushButton_22->setGeometry(QRect(100, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_22->sizePolicy().hasHeightForWidth());
        pushButton_22->setSizePolicy(sizePolicy);
        label_21 = new QLabel(frame_41);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setEnabled(true);
        label_21->setGeometry(QRect(80, 10, 101, 41));
        sizePolicy.setHeightForWidth(label_21->sizePolicy().hasHeightForWidth());
        label_21->setSizePolicy(sizePolicy);
        label_21->setFrameShape(QFrame::WinPanel);
        label_21->setFrameShadow(QFrame::Plain);
        label_22 = new QLabel(frame_41);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(10, 20, 52, 18));
        sizePolicy.setHeightForWidth(label_22->sizePolicy().hasHeightForWidth());
        label_22->setSizePolicy(sizePolicy);
        label_22->setFrameShape(QFrame::Box);
        robotframe4 = new QFrame(frame_12);
        robotframe4->setObjectName(QString::fromUtf8("robotframe4"));
        robotframe4->setEnabled(true);
        robotframe4->setGeometry(QRect(0, 0, 191, 111));
        sizePolicy.setHeightForWidth(robotframe4->sizePolicy().hasHeightForWidth());
        robotframe4->setSizePolicy(sizePolicy);
        robotframe4->setFrameShape(QFrame::WinPanel);
        robotframe4->setFrameShadow(QFrame::Sunken);
        pushButton_23 = new QPushButton(robotframe4);
        pushButton_23->setObjectName(QString::fromUtf8("pushButton_23"));
        pushButton_23->setGeometry(QRect(10, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_23->sizePolicy().hasHeightForWidth());
        pushButton_23->setSizePolicy(sizePolicy);
        pushButton_24 = new QPushButton(robotframe4);
        pushButton_24->setObjectName(QString::fromUtf8("pushButton_24"));
        pushButton_24->setGeometry(QRect(100, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_24->sizePolicy().hasHeightForWidth());
        pushButton_24->setSizePolicy(sizePolicy);
        axisposition4 = new QLabel(robotframe4);
        axisposition4->setObjectName(QString::fromUtf8("axisposition4"));
        axisposition4->setEnabled(true);
        axisposition4->setGeometry(QRect(80, 10, 101, 41));
        sizePolicy.setHeightForWidth(axisposition4->sizePolicy().hasHeightForWidth());
        axisposition4->setSizePolicy(sizePolicy);
        axisposition4->setFrameShape(QFrame::WinPanel);
        axisposition4->setFrameShadow(QFrame::Plain);
        axisname4 = new QLabel(robotframe4);
        axisname4->setObjectName(QString::fromUtf8("axisname4"));
        axisname4->setGeometry(QRect(10, 20, 52, 18));
        sizePolicy.setHeightForWidth(axisname4->sizePolicy().hasHeightForWidth());
        axisname4->setSizePolicy(sizePolicy);
        axisname4->setFrameShape(QFrame::Box);
        layoutWidget_3 = new QWidget(tab);
        layoutWidget_3->setObjectName(QString::fromUtf8("layoutWidget_3"));
        layoutWidget_3->setGeometry(QRect(1230, 10, 121, 31));
        horizontalLayout = new QHBoxLayout(layoutWidget_3);
        horizontalLayout->setObjectName(QString::fromUtf8("horizontalLayout"));
        horizontalLayout->setContentsMargins(0, 0, 0, 0);
        robotswitch = new QPushButton(layoutWidget_3);
        robotswitch->setObjectName(QString::fromUtf8("robotswitch"));
        robotswitch->setCheckable(true);
        robotswitch->setChecked(false);

        horizontalLayout->addWidget(robotswitch);

        label_37 = new QLabel(layoutWidget_3);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setEnabled(true);
        label_37->setFrameShape(QFrame::NoFrame);
        label_37->setFrameShadow(QFrame::Plain);

        horizontalLayout->addWidget(label_37);

        robotframe3 = new QFrame(tab);
        robotframe3->setObjectName(QString::fromUtf8("robotframe3"));
        robotframe3->setEnabled(true);
        robotframe3->setGeometry(QRect(420, 10, 191, 111));
        sizePolicy.setHeightForWidth(robotframe3->sizePolicy().hasHeightForWidth());
        robotframe3->setSizePolicy(sizePolicy);
        robotframe3->setFrameShape(QFrame::WinPanel);
        robotframe3->setFrameShadow(QFrame::Sunken);
        pushButton_5 = new QPushButton(robotframe3);
        pushButton_5->setObjectName(QString::fromUtf8("pushButton_5"));
        pushButton_5->setGeometry(QRect(10, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_5->sizePolicy().hasHeightForWidth());
        pushButton_5->setSizePolicy(sizePolicy);
        pushButton_6 = new QPushButton(robotframe3);
        pushButton_6->setObjectName(QString::fromUtf8("pushButton_6"));
        pushButton_6->setGeometry(QRect(100, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_6->sizePolicy().hasHeightForWidth());
        pushButton_6->setSizePolicy(sizePolicy);
        axisposition3 = new QLabel(robotframe3);
        axisposition3->setObjectName(QString::fromUtf8("axisposition3"));
        axisposition3->setEnabled(true);
        axisposition3->setGeometry(QRect(80, 10, 101, 41));
        sizePolicy.setHeightForWidth(axisposition3->sizePolicy().hasHeightForWidth());
        axisposition3->setSizePolicy(sizePolicy);
        axisposition3->setFrameShape(QFrame::WinPanel);
        axisposition3->setFrameShadow(QFrame::Plain);
        axisname3 = new QLabel(robotframe3);
        axisname3->setObjectName(QString::fromUtf8("axisname3"));
        axisname3->setGeometry(QRect(10, 20, 52, 18));
        sizePolicy.setHeightForWidth(axisname3->sizePolicy().hasHeightForWidth());
        axisname3->setSizePolicy(sizePolicy);
        axisname3->setFrameShape(QFrame::Box);
        robotframe7 = new QFrame(tab);
        robotframe7->setObjectName(QString::fromUtf8("robotframe7"));
        robotframe7->setEnabled(true);
        robotframe7->setGeometry(QRect(20, 150, 191, 111));
        sizePolicy.setHeightForWidth(robotframe7->sizePolicy().hasHeightForWidth());
        robotframe7->setSizePolicy(sizePolicy);
        robotframe7->setFrameShape(QFrame::WinPanel);
        robotframe7->setFrameShadow(QFrame::Sunken);
        pushButton_35 = new QPushButton(robotframe7);
        pushButton_35->setObjectName(QString::fromUtf8("pushButton_35"));
        pushButton_35->setGeometry(QRect(10, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_35->sizePolicy().hasHeightForWidth());
        pushButton_35->setSizePolicy(sizePolicy);
        pushButton_36 = new QPushButton(robotframe7);
        pushButton_36->setObjectName(QString::fromUtf8("pushButton_36"));
        pushButton_36->setGeometry(QRect(100, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_36->sizePolicy().hasHeightForWidth());
        pushButton_36->setSizePolicy(sizePolicy);
        axisposition7 = new QLabel(robotframe7);
        axisposition7->setObjectName(QString::fromUtf8("axisposition7"));
        axisposition7->setEnabled(true);
        axisposition7->setGeometry(QRect(80, 10, 101, 41));
        sizePolicy.setHeightForWidth(axisposition7->sizePolicy().hasHeightForWidth());
        axisposition7->setSizePolicy(sizePolicy);
        axisposition7->setFrameShape(QFrame::WinPanel);
        axisposition7->setFrameShadow(QFrame::Plain);
        axisname7 = new QLabel(robotframe7);
        axisname7->setObjectName(QString::fromUtf8("axisname7"));
        axisname7->setGeometry(QRect(10, 20, 52, 18));
        sizePolicy.setHeightForWidth(axisname7->sizePolicy().hasHeightForWidth());
        axisname7->setSizePolicy(sizePolicy);
        axisname7->setFrameShape(QFrame::Box);
        matlabtest = new QPushButton(tab);
        matlabtest->setObjectName(QString::fromUtf8("matlabtest"));
        matlabtest->setGeometry(QRect(1230, 120, 121, 24));
        frame_36 = new QFrame(tab);
        frame_36->setObjectName(QString::fromUtf8("frame_36"));
        frame_36->setGeometry(QRect(530, 670, 351, 141));
        frame_36->setFrameShape(QFrame::Box);
        frame_36->setFrameShadow(QFrame::Plain);
        lineEdit_13 = new QLineEdit(frame_36);
        lineEdit_13->setObjectName(QString::fromUtf8("lineEdit_13"));
        lineEdit_13->setGeometry(QRect(10, 10, 50, 20));
        lineEdit_13->setMaxLength(9);
        lineEdit_14 = new QLineEdit(frame_36);
        lineEdit_14->setObjectName(QString::fromUtf8("lineEdit_14"));
        lineEdit_14->setGeometry(QRect(10, 40, 50, 20));
        lineEdit_14->setMaxLength(9);
        lineEdit_15 = new QLineEdit(frame_36);
        lineEdit_15->setObjectName(QString::fromUtf8("lineEdit_15"));
        lineEdit_15->setGeometry(QRect(10, 70, 50, 20));
        lineEdit_15->setMaxLength(9);
        lineEdit_16 = new QLineEdit(frame_36);
        lineEdit_16->setObjectName(QString::fromUtf8("lineEdit_16"));
        lineEdit_16->setGeometry(QRect(10, 100, 50, 20));
        lineEdit_16->setMaxLength(9);
        lineEdit_16->setReadOnly(true);
        lineEdit_17 = new QLineEdit(frame_36);
        lineEdit_17->setObjectName(QString::fromUtf8("lineEdit_17"));
        lineEdit_17->setGeometry(QRect(70, 10, 50, 20));
        lineEdit_17->setMaxLength(9);
        lineEdit_18 = new QLineEdit(frame_36);
        lineEdit_18->setObjectName(QString::fromUtf8("lineEdit_18"));
        lineEdit_18->setGeometry(QRect(130, 10, 50, 20));
        lineEdit_18->setMaxLength(9);
        lineEdit_19 = new QLineEdit(frame_36);
        lineEdit_19->setObjectName(QString::fromUtf8("lineEdit_19"));
        lineEdit_19->setGeometry(QRect(190, 10, 50, 20));
        lineEdit_19->setMaxLength(9);
        lineEdit_20 = new QLineEdit(frame_36);
        lineEdit_20->setObjectName(QString::fromUtf8("lineEdit_20"));
        lineEdit_20->setGeometry(QRect(70, 40, 50, 20));
        lineEdit_20->setMaxLength(9);
        lineEdit_21 = new QLineEdit(frame_36);
        lineEdit_21->setObjectName(QString::fromUtf8("lineEdit_21"));
        lineEdit_21->setGeometry(QRect(130, 40, 50, 20));
        lineEdit_21->setMaxLength(9);
        lineEdit_22 = new QLineEdit(frame_36);
        lineEdit_22->setObjectName(QString::fromUtf8("lineEdit_22"));
        lineEdit_22->setGeometry(QRect(190, 40, 50, 20));
        lineEdit_22->setMaxLength(9);
        lineEdit_23 = new QLineEdit(frame_36);
        lineEdit_23->setObjectName(QString::fromUtf8("lineEdit_23"));
        lineEdit_23->setGeometry(QRect(70, 70, 50, 20));
        lineEdit_23->setMaxLength(9);
        lineEdit_24 = new QLineEdit(frame_36);
        lineEdit_24->setObjectName(QString::fromUtf8("lineEdit_24"));
        lineEdit_24->setGeometry(QRect(130, 70, 50, 20));
        lineEdit_24->setMaxLength(9);
        lineEdit_25 = new QLineEdit(frame_36);
        lineEdit_25->setObjectName(QString::fromUtf8("lineEdit_25"));
        lineEdit_25->setGeometry(QRect(190, 70, 50, 20));
        lineEdit_25->setMaxLength(9);
        lineEdit_26 = new QLineEdit(frame_36);
        lineEdit_26->setObjectName(QString::fromUtf8("lineEdit_26"));
        lineEdit_26->setGeometry(QRect(70, 100, 50, 20));
        lineEdit_26->setMaxLength(9);
        lineEdit_26->setReadOnly(true);
        lineEdit_27 = new QLineEdit(frame_36);
        lineEdit_27->setObjectName(QString::fromUtf8("lineEdit_27"));
        lineEdit_27->setGeometry(QRect(130, 100, 50, 20));
        lineEdit_27->setMaxLength(9);
        lineEdit_27->setReadOnly(true);
        lineEdit_28 = new QLineEdit(frame_36);
        lineEdit_28->setObjectName(QString::fromUtf8("lineEdit_28"));
        lineEdit_28->setGeometry(QRect(190, 100, 50, 20));
        lineEdit_28->setMaxLength(9);
        lineEdit_28->setReadOnly(true);
        label_59 = new QLabel(frame_36);
        label_59->setObjectName(QString::fromUtf8("label_59"));
        label_59->setGeometry(QRect(250, 100, 91, 21));
        label_59->setFrameShape(QFrame::Panel);
        label_59->setFrameShadow(QFrame::Raised);
        label_59->setLineWidth(3);
        label_59->setAlignment(Qt::AlignCenter);
        robotikine1 = new QPushButton(frame_36);
        robotikine1->setObjectName(QString::fromUtf8("robotikine1"));
        robotikine1->setGeometry(QRect(250, 25, 91, 24));
        robotikine2 = new QPushButton(frame_36);
        robotikine2->setObjectName(QString::fromUtf8("robotikine2"));
        robotikine2->setGeometry(QRect(250, 65, 91, 24));
        robotframe12 = new QFrame(tab);
        robotframe12->setObjectName(QString::fromUtf8("robotframe12"));
        robotframe12->setEnabled(true);
        robotframe12->setGeometry(QRect(1020, 150, 191, 111));
        sizePolicy.setHeightForWidth(robotframe12->sizePolicy().hasHeightForWidth());
        robotframe12->setSizePolicy(sizePolicy);
        robotframe12->setFrameShape(QFrame::WinPanel);
        robotframe12->setFrameShadow(QFrame::Sunken);
        pushButton_29 = new QPushButton(robotframe12);
        pushButton_29->setObjectName(QString::fromUtf8("pushButton_29"));
        pushButton_29->setGeometry(QRect(10, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_29->sizePolicy().hasHeightForWidth());
        pushButton_29->setSizePolicy(sizePolicy);
        pushButton_30 = new QPushButton(robotframe12);
        pushButton_30->setObjectName(QString::fromUtf8("pushButton_30"));
        pushButton_30->setGeometry(QRect(100, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_30->sizePolicy().hasHeightForWidth());
        pushButton_30->setSizePolicy(sizePolicy);
        axisposition12 = new QLabel(robotframe12);
        axisposition12->setObjectName(QString::fromUtf8("axisposition12"));
        axisposition12->setEnabled(true);
        axisposition12->setGeometry(QRect(80, 10, 101, 41));
        sizePolicy.setHeightForWidth(axisposition12->sizePolicy().hasHeightForWidth());
        axisposition12->setSizePolicy(sizePolicy);
        axisposition12->setFrameShape(QFrame::WinPanel);
        axisposition12->setFrameShadow(QFrame::Plain);
        axisname12 = new QLabel(robotframe12);
        axisname12->setObjectName(QString::fromUtf8("axisname12"));
        axisname12->setGeometry(QRect(10, 20, 52, 18));
        sizePolicy.setHeightForWidth(axisname12->sizePolicy().hasHeightForWidth());
        axisname12->setSizePolicy(sizePolicy);
        axisname12->setFrameShape(QFrame::Box);
        frame_29 = new QFrame(tab);
        frame_29->setObjectName(QString::fromUtf8("frame_29"));
        frame_29->setGeometry(QRect(1000, 650, 261, 161));
        frame_29->setFrameShape(QFrame::Panel);
        frame_29->setFrameShadow(QFrame::Plain);
        frame_29->setLineWidth(1);
        frame_29->setMidLineWidth(0);
        label_44 = new QLabel(frame_29);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(10, 10, 61, 21));
        label_45 = new QLabel(frame_29);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(70, 10, 16, 16));
        label_46 = new QLabel(frame_29);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(90, 10, 54, 16));
        label_47 = new QLabel(frame_29);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(160, 10, 16, 16));
        label_48 = new QLabel(frame_29);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setGeometry(QRect(180, 10, 54, 16));
        line_2 = new QFrame(frame_29);
        line_2->setObjectName(QString::fromUtf8("line_2"));
        line_2->setGeometry(QRect(10, 50, 231, 20));
        line_2->setFrameShadow(QFrame::Sunken);
        line_2->setFrameShape(QFrame::HLine);
        label_49 = new QLabel(frame_29);
        label_49->setObjectName(QString::fromUtf8("label_49"));
        label_49->setGeometry(QRect(90, 30, 54, 16));
        label_50 = new QLabel(frame_29);
        label_50->setObjectName(QString::fromUtf8("label_50"));
        label_50->setGeometry(QRect(180, 30, 54, 16));
        label_51 = new QLabel(frame_29);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setGeometry(QRect(10, 70, 54, 16));
        label_52 = new QLabel(frame_29);
        label_52->setObjectName(QString::fromUtf8("label_52"));
        label_52->setGeometry(QRect(70, 70, 16, 16));
        label_53 = new QLabel(frame_29);
        label_53->setObjectName(QString::fromUtf8("label_53"));
        label_53->setGeometry(QRect(70, 100, 16, 16));
        label_54 = new QLabel(frame_29);
        label_54->setObjectName(QString::fromUtf8("label_54"));
        label_54->setGeometry(QRect(70, 130, 16, 16));
        label_55 = new QLabel(frame_29);
        label_55->setObjectName(QString::fromUtf8("label_55"));
        label_55->setGeometry(QRect(90, 70, 54, 16));
        label_56 = new QLabel(frame_29);
        label_56->setObjectName(QString::fromUtf8("label_56"));
        label_56->setGeometry(QRect(90, 100, 54, 16));
        label_57 = new QLabel(frame_29);
        label_57->setObjectName(QString::fromUtf8("label_57"));
        label_57->setGeometry(QRect(90, 130, 54, 16));
        line_3 = new QFrame(frame_29);
        line_3->setObjectName(QString::fromUtf8("line_3"));
        line_3->setGeometry(QRect(143, 60, 20, 91));
        line_3->setFrameShape(QFrame::VLine);
        line_3->setFrameShadow(QFrame::Sunken);
        show2D = new QPushButton(frame_29);
        show2D->setObjectName(QString::fromUtf8("show2D"));
        show2D->setGeometry(QRect(160, 70, 80, 24));
        calculate3D = new QPushButton(frame_29);
        calculate3D->setObjectName(QString::fromUtf8("calculate3D"));
        calculate3D->setGeometry(QRect(160, 110, 80, 24));
        checkaccuracy = new QPushButton(frame_29);
        checkaccuracy->setObjectName(QString::fromUtf8("checkaccuracy"));
        checkaccuracy->setGeometry(QRect(10, 90, 21, 51));
        checkaccuracy->setCheckable(false);
        Robot_move = new QPushButton(frame_29);
        Robot_move->setObjectName(QString::fromUtf8("Robot_move"));
        Robot_move->setGeometry(QRect(40, 90, 21, 51));
        Robot_move->setCheckable(false);
        frame_34 = new QFrame(tab);
        frame_34->setObjectName(QString::fromUtf8("frame_34"));
        frame_34->setGeometry(QRect(20, 670, 491, 141));
        frame_34->setFrameShape(QFrame::Box);
        frame_34->setFrameShadow(QFrame::Plain);
        lineEdit = new QLineEdit(frame_34);
        lineEdit->setObjectName(QString::fromUtf8("lineEdit"));
        lineEdit->setGeometry(QRect(20, 20, 50, 20));
        lineEdit->setMaxLength(9);
        lineEdit_2 = new QLineEdit(frame_34);
        lineEdit_2->setObjectName(QString::fromUtf8("lineEdit_2"));
        lineEdit_2->setGeometry(QRect(80, 20, 50, 20));
        lineEdit_2->setMaxLength(9);
        lineEdit_3 = new QLineEdit(frame_34);
        lineEdit_3->setObjectName(QString::fromUtf8("lineEdit_3"));
        lineEdit_3->setGeometry(QRect(140, 20, 50, 20));
        lineEdit_3->setMaxLength(9);
        lineEdit_4 = new QLineEdit(frame_34);
        lineEdit_4->setObjectName(QString::fromUtf8("lineEdit_4"));
        lineEdit_4->setGeometry(QRect(200, 20, 50, 20));
        lineEdit_4->setMaxLength(9);
        lineEdit_5 = new QLineEdit(frame_34);
        lineEdit_5->setObjectName(QString::fromUtf8("lineEdit_5"));
        lineEdit_5->setGeometry(QRect(260, 20, 50, 20));
        lineEdit_5->setMaxLength(9);
        lineEdit_6 = new QLineEdit(frame_34);
        lineEdit_6->setObjectName(QString::fromUtf8("lineEdit_6"));
        lineEdit_6->setGeometry(QRect(320, 20, 50, 20));
        lineEdit_6->setMaxLength(9);
        lineEdit_7 = new QLineEdit(frame_34);
        lineEdit_7->setObjectName(QString::fromUtf8("lineEdit_7"));
        lineEdit_7->setGeometry(QRect(20, 70, 50, 20));
        lineEdit_8 = new QLineEdit(frame_34);
        lineEdit_8->setObjectName(QString::fromUtf8("lineEdit_8"));
        lineEdit_8->setGeometry(QRect(80, 70, 50, 20));
        lineEdit_9 = new QLineEdit(frame_34);
        lineEdit_9->setObjectName(QString::fromUtf8("lineEdit_9"));
        lineEdit_9->setGeometry(QRect(140, 70, 50, 20));
        lineEdit_10 = new QLineEdit(frame_34);
        lineEdit_10->setObjectName(QString::fromUtf8("lineEdit_10"));
        lineEdit_10->setGeometry(QRect(200, 70, 50, 20));
        lineEdit_11 = new QLineEdit(frame_34);
        lineEdit_11->setObjectName(QString::fromUtf8("lineEdit_11"));
        lineEdit_11->setGeometry(QRect(260, 70, 50, 20));
        lineEdit_12 = new QLineEdit(frame_34);
        lineEdit_12->setObjectName(QString::fromUtf8("lineEdit_12"));
        lineEdit_12->setGeometry(QRect(320, 70, 50, 20));
        robotkine1 = new QPushButton(frame_34);
        robotkine1->setObjectName(QString::fromUtf8("robotkine1"));
        robotkine1->setGeometry(QRect(390, 15, 90, 30));
        robotkine2 = new QPushButton(frame_34);
        robotkine2->setObjectName(QString::fromUtf8("robotkine2"));
        robotkine2->setGeometry(QRect(390, 65, 90, 30));
        label_58 = new QLabel(frame_34);
        label_58->setObjectName(QString::fromUtf8("label_58"));
        label_58->setGeometry(QRect(190, 110, 71, 21));
        label_58->setFrameShape(QFrame::Panel);
        label_58->setFrameShadow(QFrame::Raised);
        label_58->setLineWidth(3);
        label_58->setAlignment(Qt::AlignCenter);
        test_new_robot = new QPushButton(frame_34);
        test_new_robot->setObjectName(QString::fromUtf8("test_new_robot"));
        test_new_robot->setGeometry(QRect(390, 110, 80, 24));
        robotframe10 = new QFrame(tab);
        robotframe10->setObjectName(QString::fromUtf8("robotframe10"));
        robotframe10->setEnabled(true);
        robotframe10->setGeometry(QRect(620, 150, 191, 111));
        sizePolicy.setHeightForWidth(robotframe10->sizePolicy().hasHeightForWidth());
        robotframe10->setSizePolicy(sizePolicy);
        robotframe10->setFrameShape(QFrame::WinPanel);
        robotframe10->setFrameShadow(QFrame::Sunken);
        pushButton_25 = new QPushButton(robotframe10);
        pushButton_25->setObjectName(QString::fromUtf8("pushButton_25"));
        pushButton_25->setGeometry(QRect(10, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_25->sizePolicy().hasHeightForWidth());
        pushButton_25->setSizePolicy(sizePolicy);
        pushButton_26 = new QPushButton(robotframe10);
        pushButton_26->setObjectName(QString::fromUtf8("pushButton_26"));
        pushButton_26->setGeometry(QRect(100, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_26->sizePolicy().hasHeightForWidth());
        pushButton_26->setSizePolicy(sizePolicy);
        axisposition10 = new QLabel(robotframe10);
        axisposition10->setObjectName(QString::fromUtf8("axisposition10"));
        axisposition10->setEnabled(true);
        axisposition10->setGeometry(QRect(80, 10, 101, 41));
        sizePolicy.setHeightForWidth(axisposition10->sizePolicy().hasHeightForWidth());
        axisposition10->setSizePolicy(sizePolicy);
        axisposition10->setFrameShape(QFrame::WinPanel);
        axisposition10->setFrameShadow(QFrame::Plain);
        axisname10 = new QLabel(robotframe10);
        axisname10->setObjectName(QString::fromUtf8("axisname10"));
        axisname10->setGeometry(QRect(10, 20, 52, 18));
        sizePolicy.setHeightForWidth(axisname10->sizePolicy().hasHeightForWidth());
        axisname10->setSizePolicy(sizePolicy);
        axisname10->setFrameShape(QFrame::Box);
        layoutWidget_4 = new QWidget(tab);
        layoutWidget_4->setObjectName(QString::fromUtf8("layoutWidget_4"));
        layoutWidget_4->setGeometry(QRect(1270, 290, 121, 31));
        horizontalLayout_2 = new QHBoxLayout(layoutWidget_4);
        horizontalLayout_2->setObjectName(QString::fromUtf8("horizontalLayout_2"));
        horizontalLayout_2->setContentsMargins(0, 0, 0, 0);
        cameraswitch = new QPushButton(layoutWidget_4);
        cameraswitch->setObjectName(QString::fromUtf8("cameraswitch"));
        cameraswitch->setCheckable(true);
        cameraswitch->setChecked(false);

        horizontalLayout_2->addWidget(cameraswitch);

        label_43 = new QLabel(layoutWidget_4);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setEnabled(true);
        label_43->setFrameShape(QFrame::NoFrame);
        label_43->setFrameShadow(QFrame::Plain);

        horizontalLayout_2->addWidget(label_43);

        robotframe2 = new QFrame(tab);
        robotframe2->setObjectName(QString::fromUtf8("robotframe2"));
        robotframe2->setEnabled(true);
        robotframe2->setGeometry(QRect(220, 10, 191, 111));
        sizePolicy.setHeightForWidth(robotframe2->sizePolicy().hasHeightForWidth());
        robotframe2->setSizePolicy(sizePolicy);
        robotframe2->setFrameShape(QFrame::WinPanel);
        robotframe2->setFrameShadow(QFrame::Sunken);
        pushButton_3 = new QPushButton(robotframe2);
        pushButton_3->setObjectName(QString::fromUtf8("pushButton_3"));
        pushButton_3->setGeometry(QRect(10, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_3->sizePolicy().hasHeightForWidth());
        pushButton_3->setSizePolicy(sizePolicy);
        pushButton_4 = new QPushButton(robotframe2);
        pushButton_4->setObjectName(QString::fromUtf8("pushButton_4"));
        pushButton_4->setGeometry(QRect(100, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_4->sizePolicy().hasHeightForWidth());
        pushButton_4->setSizePolicy(sizePolicy);
        axisposition2 = new QLabel(robotframe2);
        axisposition2->setObjectName(QString::fromUtf8("axisposition2"));
        axisposition2->setEnabled(true);
        axisposition2->setGeometry(QRect(80, 10, 101, 41));
        sizePolicy.setHeightForWidth(axisposition2->sizePolicy().hasHeightForWidth());
        axisposition2->setSizePolicy(sizePolicy);
        axisposition2->setFrameShape(QFrame::WinPanel);
        axisposition2->setFrameShadow(QFrame::Plain);
        axisname2 = new QLabel(robotframe2);
        axisname2->setObjectName(QString::fromUtf8("axisname2"));
        axisname2->setGeometry(QRect(10, 20, 52, 18));
        sizePolicy.setHeightForWidth(axisname2->sizePolicy().hasHeightForWidth());
        axisname2->setSizePolicy(sizePolicy);
        axisname2->setFrameShape(QFrame::Box);
        line_5 = new QFrame(tab);
        line_5->setObjectName(QString::fromUtf8("line_5"));
        line_5->setGeometry(QRect(10, 268, 1391, 20));
        line_5->setFrameShadow(QFrame::Raised);
        line_5->setLineWidth(2);
        line_5->setFrameShape(QFrame::HLine);
        getposition = new QPushButton(tab);
        getposition->setObjectName(QString::fromUtf8("getposition"));
        getposition->setGeometry(QRect(1270, 370, 80, 24));
        robotframe11 = new QFrame(tab);
        robotframe11->setObjectName(QString::fromUtf8("robotframe11"));
        robotframe11->setEnabled(true);
        robotframe11->setGeometry(QRect(820, 150, 191, 111));
        sizePolicy.setHeightForWidth(robotframe11->sizePolicy().hasHeightForWidth());
        robotframe11->setSizePolicy(sizePolicy);
        robotframe11->setFrameShape(QFrame::WinPanel);
        robotframe11->setFrameShadow(QFrame::Sunken);
        pushButton_31 = new QPushButton(robotframe11);
        pushButton_31->setObjectName(QString::fromUtf8("pushButton_31"));
        pushButton_31->setGeometry(QRect(10, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_31->sizePolicy().hasHeightForWidth());
        pushButton_31->setSizePolicy(sizePolicy);
        pushButton_32 = new QPushButton(robotframe11);
        pushButton_32->setObjectName(QString::fromUtf8("pushButton_32"));
        pushButton_32->setGeometry(QRect(100, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_32->sizePolicy().hasHeightForWidth());
        pushButton_32->setSizePolicy(sizePolicy);
        axisposition11 = new QLabel(robotframe11);
        axisposition11->setObjectName(QString::fromUtf8("axisposition11"));
        axisposition11->setEnabled(true);
        axisposition11->setGeometry(QRect(80, 10, 101, 41));
        sizePolicy.setHeightForWidth(axisposition11->sizePolicy().hasHeightForWidth());
        axisposition11->setSizePolicy(sizePolicy);
        axisposition11->setFrameShape(QFrame::WinPanel);
        axisposition11->setFrameShadow(QFrame::Plain);
        axisname11 = new QLabel(robotframe11);
        axisname11->setObjectName(QString::fromUtf8("axisname11"));
        axisname11->setGeometry(QRect(10, 20, 52, 18));
        sizePolicy.setHeightForWidth(axisname11->sizePolicy().hasHeightForWidth());
        axisname11->setSizePolicy(sizePolicy);
        axisname11->setFrameShape(QFrame::Box);
        stop_button = new QPushButton(tab);
        stop_button->setObjectName(QString::fromUtf8("stop_button"));
        stop_button->setGeometry(QRect(1230, 60, 101, 41));
        stop_button->setStyleSheet(QString::fromUtf8("font: 12pt \"Microsoft YaHei UI\";\n"
"border-color: rgb(255, 255, 0);\n"
"background-color: rgb(170, 0, 0);\n"
""));
        robotframe1 = new QFrame(tab);
        robotframe1->setObjectName(QString::fromUtf8("robotframe1"));
        robotframe1->setEnabled(true);
        robotframe1->setGeometry(QRect(20, 10, 191, 111));
        sizePolicy.setHeightForWidth(robotframe1->sizePolicy().hasHeightForWidth());
        robotframe1->setSizePolicy(sizePolicy);
        robotframe1->setFrameShape(QFrame::WinPanel);
        robotframe1->setFrameShadow(QFrame::Sunken);
        pushButton = new QPushButton(robotframe1);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(10, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton->sizePolicy().hasHeightForWidth());
        pushButton->setSizePolicy(sizePolicy);
        pushButton_2 = new QPushButton(robotframe1);
        pushButton_2->setObjectName(QString::fromUtf8("pushButton_2"));
        pushButton_2->setGeometry(QRect(100, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_2->sizePolicy().hasHeightForWidth());
        pushButton_2->setSizePolicy(sizePolicy);
        axisposition1 = new QLabel(robotframe1);
        axisposition1->setObjectName(QString::fromUtf8("axisposition1"));
        axisposition1->setEnabled(true);
        axisposition1->setGeometry(QRect(80, 10, 101, 41));
        sizePolicy.setHeightForWidth(axisposition1->sizePolicy().hasHeightForWidth());
        axisposition1->setSizePolicy(sizePolicy);
        axisposition1->setFrameShape(QFrame::WinPanel);
        axisposition1->setFrameShadow(QFrame::Plain);
        axisname1 = new QLabel(robotframe1);
        axisname1->setObjectName(QString::fromUtf8("axisname1"));
        axisname1->setGeometry(QRect(10, 20, 52, 18));
        sizePolicy.setHeightForWidth(axisname1->sizePolicy().hasHeightForWidth());
        axisname1->setSizePolicy(sizePolicy);
        axisname1->setFrameShape(QFrame::Box);
        robotframe8 = new QFrame(tab);
        robotframe8->setObjectName(QString::fromUtf8("robotframe8"));
        robotframe8->setEnabled(true);
        robotframe8->setGeometry(QRect(220, 150, 191, 111));
        sizePolicy.setHeightForWidth(robotframe8->sizePolicy().hasHeightForWidth());
        robotframe8->setSizePolicy(sizePolicy);
        robotframe8->setFrameShape(QFrame::WinPanel);
        robotframe8->setFrameShadow(QFrame::Sunken);
        pushButton_27 = new QPushButton(robotframe8);
        pushButton_27->setObjectName(QString::fromUtf8("pushButton_27"));
        pushButton_27->setGeometry(QRect(10, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_27->sizePolicy().hasHeightForWidth());
        pushButton_27->setSizePolicy(sizePolicy);
        pushButton_28 = new QPushButton(robotframe8);
        pushButton_28->setObjectName(QString::fromUtf8("pushButton_28"));
        pushButton_28->setGeometry(QRect(100, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_28->sizePolicy().hasHeightForWidth());
        pushButton_28->setSizePolicy(sizePolicy);
        axisposition8 = new QLabel(robotframe8);
        axisposition8->setObjectName(QString::fromUtf8("axisposition8"));
        axisposition8->setEnabled(true);
        axisposition8->setGeometry(QRect(80, 10, 101, 41));
        sizePolicy.setHeightForWidth(axisposition8->sizePolicy().hasHeightForWidth());
        axisposition8->setSizePolicy(sizePolicy);
        axisposition8->setFrameShape(QFrame::WinPanel);
        axisposition8->setFrameShadow(QFrame::Plain);
        axisname8 = new QLabel(robotframe8);
        axisname8->setObjectName(QString::fromUtf8("axisname8"));
        axisname8->setGeometry(QRect(10, 20, 52, 18));
        sizePolicy.setHeightForWidth(axisname8->sizePolicy().hasHeightForWidth());
        axisname8->setSizePolicy(sizePolicy);
        axisname8->setFrameShape(QFrame::Box);
        robotframe6 = new QFrame(tab);
        robotframe6->setObjectName(QString::fromUtf8("robotframe6"));
        robotframe6->setEnabled(true);
        robotframe6->setGeometry(QRect(1020, 10, 191, 111));
        sizePolicy.setHeightForWidth(robotframe6->sizePolicy().hasHeightForWidth());
        robotframe6->setSizePolicy(sizePolicy);
        robotframe6->setFrameShape(QFrame::WinPanel);
        robotframe6->setFrameShadow(QFrame::Sunken);
        pushButton_11 = new QPushButton(robotframe6);
        pushButton_11->setObjectName(QString::fromUtf8("pushButton_11"));
        pushButton_11->setGeometry(QRect(10, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_11->sizePolicy().hasHeightForWidth());
        pushButton_11->setSizePolicy(sizePolicy);
        pushButton_12 = new QPushButton(robotframe6);
        pushButton_12->setObjectName(QString::fromUtf8("pushButton_12"));
        pushButton_12->setGeometry(QRect(100, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_12->sizePolicy().hasHeightForWidth());
        pushButton_12->setSizePolicy(sizePolicy);
        axisposition6 = new QLabel(robotframe6);
        axisposition6->setObjectName(QString::fromUtf8("axisposition6"));
        axisposition6->setEnabled(true);
        axisposition6->setGeometry(QRect(80, 10, 101, 41));
        sizePolicy.setHeightForWidth(axisposition6->sizePolicy().hasHeightForWidth());
        axisposition6->setSizePolicy(sizePolicy);
        axisposition6->setFrameShape(QFrame::WinPanel);
        axisposition6->setFrameShadow(QFrame::Plain);
        axisname6 = new QLabel(robotframe6);
        axisname6->setObjectName(QString::fromUtf8("axisname6"));
        axisname6->setGeometry(QRect(10, 20, 52, 18));
        sizePolicy.setHeightForWidth(axisname6->sizePolicy().hasHeightForWidth());
        axisname6->setSizePolicy(sizePolicy);
        axisname6->setFrameShape(QFrame::Box);
        phoframe1 = new QLabel(tab);
        phoframe1->setObjectName(QString::fromUtf8("phoframe1"));
        phoframe1->setGeometry(QRect(20, 290, 480, 360));
        phoframe1->setFrameShape(QFrame::Box);
        phoframe1->setLineWidth(2);
        phoframe1->setAlignment(Qt::AlignCenter);
        showtool = new QPushButton(tab);
        showtool->setObjectName(QString::fromUtf8("showtool"));
        showtool->setGeometry(QRect(1270, 410, 91, 31));
        robotframe5 = new QFrame(tab);
        robotframe5->setObjectName(QString::fromUtf8("robotframe5"));
        robotframe5->setEnabled(true);
        robotframe5->setGeometry(QRect(820, 10, 191, 111));
        sizePolicy.setHeightForWidth(robotframe5->sizePolicy().hasHeightForWidth());
        robotframe5->setSizePolicy(sizePolicy);
        robotframe5->setFrameShape(QFrame::WinPanel);
        robotframe5->setFrameShadow(QFrame::Sunken);
        pushButton_9 = new QPushButton(robotframe5);
        pushButton_9->setObjectName(QString::fromUtf8("pushButton_9"));
        pushButton_9->setGeometry(QRect(10, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_9->sizePolicy().hasHeightForWidth());
        pushButton_9->setSizePolicy(sizePolicy);
        pushButton_10 = new QPushButton(robotframe5);
        pushButton_10->setObjectName(QString::fromUtf8("pushButton_10"));
        pushButton_10->setGeometry(QRect(100, 70, 80, 24));
        sizePolicy.setHeightForWidth(pushButton_10->sizePolicy().hasHeightForWidth());
        pushButton_10->setSizePolicy(sizePolicy);
        axisposition5 = new QLabel(robotframe5);
        axisposition5->setObjectName(QString::fromUtf8("axisposition5"));
        axisposition5->setEnabled(true);
        axisposition5->setGeometry(QRect(80, 10, 101, 41));
        sizePolicy.setHeightForWidth(axisposition5->sizePolicy().hasHeightForWidth());
        axisposition5->setSizePolicy(sizePolicy);
        axisposition5->setFrameShape(QFrame::WinPanel);
        axisposition5->setFrameShadow(QFrame::Plain);
        axisname5 = new QLabel(robotframe5);
        axisname5->setObjectName(QString::fromUtf8("axisname5"));
        axisname5->setGeometry(QRect(10, 20, 52, 18));
        sizePolicy.setHeightForWidth(axisname5->sizePolicy().hasHeightForWidth());
        axisname5->setSizePolicy(sizePolicy);
        axisname5->setFrameShape(QFrame::Box);
        phoframe2 = new QLabel(tab);
        phoframe2->setObjectName(QString::fromUtf8("phoframe2"));
        phoframe2->setGeometry(QRect(500, 290, 480, 360));
        phoframe2->setFrameShape(QFrame::Box);
        phoframe2->setFrameShadow(QFrame::Plain);
        phoframe2->setLineWidth(2);
        phoframe2->setAlignment(Qt::AlignCenter);
        pushButton_49 = new QPushButton(tab);
        pushButton_49->setObjectName(QString::fromUtf8("pushButton_49"));
        pushButton_49->setGeometry(QRect(1230, 160, 80, 24));
        showpic = new QPushButton(tab);
        showpic->setObjectName(QString::fromUtf8("showpic"));
        showpic->setGeometry(QRect(1270, 330, 91, 24));
        Robot_select = new QComboBox(tab);
        Robot_select->addItem(QString());
        Robot_select->addItem(QString());
        Robot_select->setObjectName(QString::fromUtf8("Robot_select"));
        Robot_select->setGeometry(QRect(900, 770, 81, 31));
        pushButton_43 = new QPushButton(tab);
        pushButton_43->setObjectName(QString::fromUtf8("pushButton_43"));
        pushButton_43->setGeometry(QRect(1270, 470, 80, 24));
        pushButton_44 = new QPushButton(tab);
        pushButton_44->setObjectName(QString::fromUtf8("pushButton_44"));
        pushButton_44->setGeometry(QRect(1000, 562, 31, 24));
        pushButton_45 = new QPushButton(tab);
        pushButton_45->setObjectName(QString::fromUtf8("pushButton_45"));
        pushButton_45->setGeometry(QRect(1100, 562, 31, 24));
        pushButton_46 = new QPushButton(tab);
        pushButton_46->setObjectName(QString::fromUtf8("pushButton_46"));
        pushButton_46->setGeometry(QRect(1150, 562, 31, 24));
        pushButton_47 = new QPushButton(tab);
        pushButton_47->setObjectName(QString::fromUtf8("pushButton_47"));
        pushButton_47->setGeometry(QRect(1200, 562, 31, 24));
        pushButton_48 = new QPushButton(tab);
        pushButton_48->setObjectName(QString::fromUtf8("pushButton_48"));
        pushButton_48->setGeometry(QRect(1250, 562, 31, 24));
        pushButton_50 = new QPushButton(tab);
        pushButton_50->setObjectName(QString::fromUtf8("pushButton_50"));
        pushButton_50->setGeometry(QRect(1300, 562, 31, 24));
        pushButton_51 = new QPushButton(tab);
        pushButton_51->setObjectName(QString::fromUtf8("pushButton_51"));
        pushButton_51->setGeometry(QRect(1050, 562, 31, 24));
        pushButton_52 = new QPushButton(tab);
        pushButton_52->setObjectName(QString::fromUtf8("pushButton_52"));
        pushButton_52->setGeometry(QRect(1000, 610, 51, 24));
        pushButton_53 = new QPushButton(tab);
        pushButton_53->setObjectName(QString::fromUtf8("pushButton_53"));
        pushButton_53->setGeometry(QRect(1060, 610, 51, 24));
        pushButton_54 = new QPushButton(tab);
        pushButton_54->setObjectName(QString::fromUtf8("pushButton_54"));
        pushButton_54->setGeometry(QRect(1120, 610, 51, 24));
        pushButton_55 = new QPushButton(tab);
        pushButton_55->setObjectName(QString::fromUtf8("pushButton_55"));
        pushButton_55->setGeometry(QRect(1195, 610, 51, 24));
        pushButton_56 = new QPushButton(tab);
        pushButton_56->setObjectName(QString::fromUtf8("pushButton_56"));
        pushButton_56->setGeometry(QRect(1315, 610, 51, 24));
        pushButton_57 = new QPushButton(tab);
        pushButton_57->setObjectName(QString::fromUtf8("pushButton_57"));
        pushButton_57->setGeometry(QRect(1255, 610, 51, 24));
        pushButton_58 = new QPushButton(tab);
        pushButton_58->setObjectName(QString::fromUtf8("pushButton_58"));
        pushButton_58->setGeometry(QRect(1350, 562, 31, 24));
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QString::fromUtf8("tab_2"));
        frame = new QFrame(tab_2);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(30, 30, 151, 191));
        frame->setFrameShape(QFrame::Box);
        frame->setFrameShadow(QFrame::Sunken);
        layoutWidget = new QWidget(frame);
        layoutWidget->setObjectName(QString::fromUtf8("layoutWidget"));
        layoutWidget->setGeometry(QRect(10, 20, 132, 58));
        horizontalLayout_3 = new QHBoxLayout(layoutWidget);
        horizontalLayout_3->setObjectName(QString::fromUtf8("horizontalLayout_3"));
        horizontalLayout_3->setContentsMargins(0, 0, 0, 0);
        verticalLayout_2 = new QVBoxLayout();
        verticalLayout_2->setObjectName(QString::fromUtf8("verticalLayout_2"));
        label = new QLabel(layoutWidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setFrameShape(QFrame::NoFrame);
        label->setFrameShadow(QFrame::Plain);
        label->setLineWidth(1);

        verticalLayout_2->addWidget(label);

        label_3 = new QLabel(layoutWidget);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setFrameShape(QFrame::NoFrame);
        label_3->setFrameShadow(QFrame::Plain);
        label_3->setLineWidth(1);

        verticalLayout_2->addWidget(label_3);


        horizontalLayout_3->addLayout(verticalLayout_2);

        verticalLayout = new QVBoxLayout();
        verticalLayout->setObjectName(QString::fromUtf8("verticalLayout"));
        comboBox = new QComboBox(layoutWidget);
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->setObjectName(QString::fromUtf8("comboBox"));

        verticalLayout->addWidget(comboBox);

        comboBox_2 = new QComboBox(layoutWidget);
        comboBox_2->addItem(QString());
        comboBox_2->addItem(QString());
        comboBox_2->setObjectName(QString::fromUtf8("comboBox_2"));

        verticalLayout->addWidget(comboBox_2);


        horizontalLayout_3->addLayout(verticalLayout);

        layoutWidget1 = new QWidget(frame);
        layoutWidget1->setObjectName(QString::fromUtf8("layoutWidget1"));
        layoutWidget1->setGeometry(QRect(10, 110, 131, 56));
        verticalLayout_3 = new QVBoxLayout(layoutWidget1);
        verticalLayout_3->setObjectName(QString::fromUtf8("verticalLayout_3"));
        verticalLayout_3->setContentsMargins(0, 0, 0, 0);
        port_turnon = new QPushButton(layoutWidget1);
        port_turnon->setObjectName(QString::fromUtf8("port_turnon"));

        verticalLayout_3->addWidget(port_turnon);

        pushButton_40 = new QPushButton(layoutWidget1);
        pushButton_40->setObjectName(QString::fromUtf8("pushButton_40"));

        verticalLayout_3->addWidget(pushButton_40);

        label_2 = new QLabel(tab_2);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(40, 20, 81, 21));
        label_2->setTabletTracking(false);
        label_2->setFocusPolicy(Qt::NoFocus);
        label_2->setFrameShape(QFrame::NoFrame);
        label_2->setFrameShadow(QFrame::Sunken);
        layoutWidget2 = new QWidget(tab_2);
        layoutWidget2->setObjectName(QString::fromUtf8("layoutWidget2"));
        layoutWidget2->setGeometry(QRect(202, 190, 271, 26));
        horizontalLayout_4 = new QHBoxLayout(layoutWidget2);
        horizontalLayout_4->setObjectName(QString::fromUtf8("horizontalLayout_4"));
        horizontalLayout_4->setContentsMargins(0, 0, 0, 0);
        telegram_Edit = new QLineEdit(layoutWidget2);
        telegram_Edit->setObjectName(QString::fromUtf8("telegram_Edit"));
        telegram_Edit->setEnabled(true);

        horizontalLayout_4->addWidget(telegram_Edit);

        sent_telegram = new QPushButton(layoutWidget2);
        sent_telegram->setObjectName(QString::fromUtf8("sent_telegram"));

        horizontalLayout_4->addWidget(sent_telegram);

        readport_text = new QTextEdit(tab_2);
        readport_text->setObjectName(QString::fromUtf8("readport_text"));
        readport_text->setGeometry(QRect(200, 30, 271, 151));
        readport_text->setFrameShape(QFrame::Box);
        readport_text->setFrameShadow(QFrame::Sunken);
        readport_text->setReadOnly(false);
        frame_2 = new QFrame(tab_2);
        frame_2->setObjectName(QString::fromUtf8("frame_2"));
        frame_2->setGeometry(QRect(30, 250, 441, 60));
        frame_2->setFrameShape(QFrame::Box);
        frame_2->setFrameShadow(QFrame::Sunken);
        formLayout = new QFormLayout(frame_2);
        formLayout->setObjectName(QString::fromUtf8("formLayout"));
        label_4 = new QLabel(frame_2);
        label_4->setObjectName(QString::fromUtf8("label_4"));

        formLayout->setWidget(0, QFormLayout::LabelRole, label_4);

        label_5 = new QLabel(frame_2);
        label_5->setObjectName(QString::fromUtf8("label_5"));

        formLayout->setWidget(1, QFormLayout::LabelRole, label_5);

        horizontalSlider_2 = new QSlider(frame_2);
        horizontalSlider_2->setObjectName(QString::fromUtf8("horizontalSlider_2"));
        horizontalSlider_2->setMinimum(260);
        horizontalSlider_2->setMaximum(380);
        horizontalSlider_2->setSingleStep(12);
        horizontalSlider_2->setPageStep(12);
        horizontalSlider_2->setValue(380);
        horizontalSlider_2->setOrientation(Qt::Horizontal);
        horizontalSlider_2->setTickPosition(QSlider::TicksBothSides);

        formLayout->setWidget(1, QFormLayout::FieldRole, horizontalSlider_2);

        horizontalSlider_1 = new QSlider(frame_2);
        horizontalSlider_1->setObjectName(QString::fromUtf8("horizontalSlider_1"));
        horizontalSlider_1->setMinimum(260);
        horizontalSlider_1->setMaximum(380);
        horizontalSlider_1->setSingleStep(12);
        horizontalSlider_1->setPageStep(12);
        horizontalSlider_1->setValue(380);
        horizontalSlider_1->setOrientation(Qt::Horizontal);
        horizontalSlider_1->setTickPosition(QSlider::TicksBothSides);

        formLayout->setWidget(0, QFormLayout::FieldRole, horizontalSlider_1);

        label_6 = new QLabel(tab_2);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(40, 240, 81, 21));
        label_6->setTabletTracking(false);
        label_6->setFocusPolicy(Qt::NoFocus);
        label_6->setFrameShape(QFrame::NoFrame);
        label_6->setFrameShadow(QFrame::Sunken);
        miniCamera_label1 = new QLabel(tab_2);
        miniCamera_label1->setObjectName(QString::fromUtf8("miniCamera_label1"));
        miniCamera_label1->setGeometry(QRect(30, 330, 480, 480));
        miniCamera_label1->setFrameShape(QFrame::Box);
        miniCamera_label1->setLineWidth(2);
        miniCamera_label2 = new QLabel(tab_2);
        miniCamera_label2->setObjectName(QString::fromUtf8("miniCamera_label2"));
        miniCamera_label2->setGeometry(QRect(530, 330, 480, 480));
        miniCamera_label2->setFrameShape(QFrame::Box);
        miniCamera_label2->setLineWidth(2);
        pushButton_38 = new QPushButton(tab_2);
        pushButton_38->setObjectName(QString::fromUtf8("pushButton_38"));
        pushButton_38->setGeometry(QRect(500, 280, 111, 31));
        pushButton_38->setCheckable(true);
        pushButton_38->setChecked(false);
        pushButton_39 = new QPushButton(tab_2);
        pushButton_39->setObjectName(QString::fromUtf8("pushButton_39"));
        pushButton_39->setGeometry(QRect(630, 280, 81, 31));
        pushButton_41 = new QPushButton(tab_2);
        pushButton_41->setObjectName(QString::fromUtf8("pushButton_41"));
        pushButton_41->setGeometry(QRect(740, 280, 80, 31));
        pushButton_42 = new QPushButton(tab_2);
        pushButton_42->setObjectName(QString::fromUtf8("pushButton_42"));
        pushButton_42->setGeometry(QRect(854, 280, 80, 31));
        stop_button_2 = new QPushButton(tab_2);
        stop_button_2->setObjectName(QString::fromUtf8("stop_button_2"));
        stop_button_2->setGeometry(QRect(520, 30, 101, 41));
        stop_button_2->setStyleSheet(QString::fromUtf8("font: 12pt \"Microsoft YaHei UI\";\n"
"border-color: rgb(255, 255, 0);\n"
"background-color: rgb(170, 0, 0);\n"
""));
        pushButton_37 = new QPushButton(tab_2);
        pushButton_37->setObjectName(QString::fromUtf8("pushButton_37"));
        pushButton_37->setGeometry(QRect(970, 280, 81, 31));
        tabWidget->addTab(tab_2, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QString::fromUtf8("tab_3"));
        Model_predict = new QPushButton(tab_3);
        Model_predict->setObjectName(QString::fromUtf8("Model_predict"));
        Model_predict->setEnabled(false);
        Model_predict->setGeometry(QRect(133, 705, 80, 24));
        Model_predict->setFlat(false);
        Py_initialize = new QPushButton(tab_3);
        Py_initialize->setObjectName(QString::fromUtf8("Py_initialize"));
        Py_initialize->setGeometry(QRect(23, 705, 91, 24));
        predict_pic1 = new QLabel(tab_3);
        predict_pic1->setObjectName(QString::fromUtf8("predict_pic1"));
        predict_pic1->setGeometry(QRect(20, 30, 600, 450));
        predict_pic1->setFrameShape(QFrame::Box);
        predict_pic2 = new QLabel(tab_3);
        predict_pic2->setObjectName(QString::fromUtf8("predict_pic2"));
        predict_pic2->setGeometry(QRect(630, 30, 600, 450));
        predict_pic2->setFrameShape(QFrame::Box);
        tabWidget->addTab(tab_3, QString());
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1400, 21));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(1);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "\346\216\247\345\210\266\345\217\260\347\225\214\351\235\242", nullptr));
        pushButton_33->setText(QCoreApplication::translate("MainWindow", "+", nullptr));
        pushButton_34->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        axisposition9->setText(QString());
        axisname9->setText(QCoreApplication::translate("MainWindow", "\345\205\263\350\212\2029\357\274\232", nullptr));
        CalibrateC_R2->setText(QCoreApplication::translate("MainWindow", "\346\211\213\347\234\274\346\240\207\345\256\232", nullptr));
        phoframe3->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p align=\"center\">\345\276\256\345\236\213\347\233\270\346\234\272\347\224\273\351\235\242</p></body></html>", nullptr));
        pushButton_7->setText(QCoreApplication::translate("MainWindow", "+", nullptr));
        pushButton_8->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        label_7->setText(QString());
        label_8->setText(QCoreApplication::translate("MainWindow", "\345\205\263\350\212\2021\357\274\232", nullptr));
        pushButton_13->setText(QCoreApplication::translate("MainWindow", "+", nullptr));
        pushButton_14->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        label_13->setText(QString());
        label_14->setText(QCoreApplication::translate("MainWindow", "\345\205\263\350\212\2021\357\274\232", nullptr));
        pushButton_15->setText(QCoreApplication::translate("MainWindow", "+", nullptr));
        pushButton_16->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        label_15->setText(QString());
        label_16->setText(QCoreApplication::translate("MainWindow", "\345\205\263\350\212\2021\357\274\232", nullptr));
        pushButton_17->setText(QCoreApplication::translate("MainWindow", "+", nullptr));
        pushButton_18->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        label_17->setText(QString());
        label_18->setText(QCoreApplication::translate("MainWindow", "\345\205\263\350\212\2021\357\274\232", nullptr));
        pushButton_19->setText(QCoreApplication::translate("MainWindow", "+", nullptr));
        pushButton_20->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        label_19->setText(QString());
        label_20->setText(QCoreApplication::translate("MainWindow", "\345\205\263\350\212\2021\357\274\232", nullptr));
        pushButton_21->setText(QCoreApplication::translate("MainWindow", "+", nullptr));
        pushButton_22->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        label_21->setText(QString());
        label_22->setText(QCoreApplication::translate("MainWindow", "\345\205\263\350\212\2021\357\274\232", nullptr));
        pushButton_23->setText(QCoreApplication::translate("MainWindow", "+", nullptr));
        pushButton_24->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        axisposition4->setText(QString());
        axisname4->setText(QCoreApplication::translate("MainWindow", "\345\205\263\350\212\2024\357\274\232", nullptr));
        robotswitch->setText(QCoreApplication::translate("MainWindow", "\346\234\272\345\231\250\344\272\272\345\274\200\345\205\263", nullptr));
        label_37->setText(QString());
        pushButton_5->setText(QCoreApplication::translate("MainWindow", "+", nullptr));
        pushButton_6->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        axisposition3->setText(QString());
        axisname3->setText(QCoreApplication::translate("MainWindow", "\345\205\263\350\212\2023\357\274\232", nullptr));
        pushButton_35->setText(QCoreApplication::translate("MainWindow", "+", nullptr));
        pushButton_36->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        axisposition7->setText(QString());
        axisname7->setText(QCoreApplication::translate("MainWindow", "\345\205\263\350\212\2027\357\274\232", nullptr));
        matlabtest->setText(QCoreApplication::translate("MainWindow", "TEST_MATLAB", nullptr));
        lineEdit_13->setText(QString());
        lineEdit_14->setText(QString());
        lineEdit_15->setText(QString());
        lineEdit_16->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        lineEdit_17->setText(QString());
        lineEdit_18->setText(QString());
        lineEdit_19->setText(QString());
        lineEdit_20->setText(QString());
        lineEdit_21->setText(QString());
        lineEdit_22->setText(QString());
        lineEdit_23->setText(QString());
        lineEdit_24->setText(QString());
        lineEdit_25->setText(QString());
        lineEdit_26->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        lineEdit_27->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        lineEdit_28->setText(QCoreApplication::translate("MainWindow", "1", nullptr));
        label_59->setText(QCoreApplication::translate("MainWindow", "\351\200\206\345\220\221\350\277\220\345\212\250\345\255\246", nullptr));
        robotikine1->setText(QCoreApplication::translate("MainWindow", "Arm1_motion", nullptr));
        robotikine2->setText(QCoreApplication::translate("MainWindow", "Arm2_motion", nullptr));
        pushButton_29->setText(QCoreApplication::translate("MainWindow", "+", nullptr));
        pushButton_30->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        axisposition12->setText(QString());
        axisname12->setText(QCoreApplication::translate("MainWindow", "\345\205\263\350\212\20212\357\274\232", nullptr));
        label_44->setText(QCoreApplication::translate("MainWindow", "\345\233\276\345\203\217\345\235\220\346\240\207\357\274\232", nullptr));
        label_45->setText(QCoreApplication::translate("MainWindow", "X\357\274\232", nullptr));
        label_46->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        label_47->setText(QCoreApplication::translate("MainWindow", "Y\357\274\232", nullptr));
        label_48->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        label_49->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        label_50->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        label_51->setText(QCoreApplication::translate("MainWindow", "\344\270\211\347\273\264\345\235\220\346\240\207\357\274\232", nullptr));
        label_52->setText(QCoreApplication::translate("MainWindow", "X\357\274\232", nullptr));
        label_53->setText(QCoreApplication::translate("MainWindow", "Y\357\274\232", nullptr));
        label_54->setText(QCoreApplication::translate("MainWindow", "Z:", nullptr));
        label_55->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        label_56->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        label_57->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        show2D->setText(QCoreApplication::translate("MainWindow", "Show 2D ", nullptr));
        calculate3D->setText(QCoreApplication::translate("MainWindow", "Calculate3D ", nullptr));
        checkaccuracy->setText(QCoreApplication::translate("MainWindow", "C", nullptr));
        Robot_move->setText(QCoreApplication::translate("MainWindow", "Go", nullptr));
        lineEdit->setText(QString());
        lineEdit_2->setText(QString());
        lineEdit_7->setText(QString());
        lineEdit_8->setText(QString());
        lineEdit_9->setText(QString());
        lineEdit_10->setText(QString());
        lineEdit_11->setText(QString());
        lineEdit_12->setText(QString());
        robotkine1->setText(QCoreApplication::translate("MainWindow", "Arm1_motion", nullptr));
        robotkine2->setText(QCoreApplication::translate("MainWindow", "Arm2_motion", nullptr));
        label_58->setText(QCoreApplication::translate("MainWindow", "\346\255\243\345\220\221\350\277\220\345\212\250\345\255\246", nullptr));
        test_new_robot->setText(QCoreApplication::translate("MainWindow", "test", nullptr));
        pushButton_25->setText(QCoreApplication::translate("MainWindow", "+", nullptr));
        pushButton_26->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        axisposition10->setText(QString());
        axisname10->setText(QCoreApplication::translate("MainWindow", "\345\205\263\350\212\20210\357\274\232", nullptr));
        cameraswitch->setText(QCoreApplication::translate("MainWindow", "\347\233\270\346\234\272\345\274\200\345\205\263", nullptr));
        label_43->setText(QString());
        pushButton_3->setText(QCoreApplication::translate("MainWindow", "+", nullptr));
        pushButton_4->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        axisposition2->setText(QString());
        axisname2->setText(QCoreApplication::translate("MainWindow", "\345\205\263\350\212\2022\357\274\232", nullptr));
        getposition->setText(QCoreApplication::translate("MainWindow", "Get position", nullptr));
        pushButton_31->setText(QCoreApplication::translate("MainWindow", "+", nullptr));
        pushButton_32->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        axisposition11->setText(QString());
        axisname11->setText(QCoreApplication::translate("MainWindow", "\345\205\263\350\212\20211\357\274\232", nullptr));
        stop_button->setText(QCoreApplication::translate("MainWindow", "STOP", nullptr));
        pushButton->setText(QCoreApplication::translate("MainWindow", "+", nullptr));
        pushButton_2->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        axisposition1->setText(QString());
        axisname1->setText(QCoreApplication::translate("MainWindow", "\345\205\263\350\212\2021\357\274\232", nullptr));
        pushButton_27->setText(QCoreApplication::translate("MainWindow", "+", nullptr));
        pushButton_28->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        axisposition8->setText(QString());
        axisname8->setText(QCoreApplication::translate("MainWindow", "\345\205\263\350\212\2028\357\274\232", nullptr));
        pushButton_11->setText(QCoreApplication::translate("MainWindow", "+", nullptr));
        pushButton_12->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        axisposition6->setText(QString());
        axisname6->setText(QCoreApplication::translate("MainWindow", "\345\205\263\350\212\2026\357\274\232", nullptr));
        phoframe1->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p align=\"center\">\347\233\270\346\234\272\344\270\200\347\224\273\351\235\242</p></body></html>", nullptr));
        showtool->setText(QCoreApplication::translate("MainWindow", "Show_tool", nullptr));
        pushButton_9->setText(QCoreApplication::translate("MainWindow", "+", nullptr));
        pushButton_10->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        axisposition5->setText(QString());
        axisname5->setText(QCoreApplication::translate("MainWindow", "\345\205\263\350\212\2025\357\274\232", nullptr));
        phoframe2->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p align=\"center\">\347\233\270\346\234\272\344\272\214\347\224\273\351\235\242</p></body></html>", nullptr));
        pushButton_49->setText(QCoreApplication::translate("MainWindow", "rect", nullptr));
        showpic->setText(QCoreApplication::translate("MainWindow", "Showpic", nullptr));
        Robot_select->setItemText(0, QCoreApplication::translate("MainWindow", "Robot1", nullptr));
        Robot_select->setItemText(1, QCoreApplication::translate("MainWindow", "Robot2", nullptr));

        pushButton_43->setText(QCoreApplication::translate("MainWindow", "test_v", nullptr));
        pushButton_44->setText(QCoreApplication::translate("MainWindow", "1", nullptr));
        pushButton_45->setText(QCoreApplication::translate("MainWindow", "3", nullptr));
        pushButton_46->setText(QCoreApplication::translate("MainWindow", "4", nullptr));
        pushButton_47->setText(QCoreApplication::translate("MainWindow", "5", nullptr));
        pushButton_48->setText(QCoreApplication::translate("MainWindow", "6", nullptr));
        pushButton_50->setText(QCoreApplication::translate("MainWindow", "7", nullptr));
        pushButton_51->setText(QCoreApplication::translate("MainWindow", "2", nullptr));
        pushButton_52->setText(QCoreApplication::translate("MainWindow", "1_\346\211\223\345\274\200", nullptr));
        pushButton_53->setText(QCoreApplication::translate("MainWindow", "1_\345\215\212\351\227\255", nullptr));
        pushButton_54->setText(QCoreApplication::translate("MainWindow", "1_\351\227\255\345\220\210", nullptr));
        pushButton_55->setText(QCoreApplication::translate("MainWindow", "2_\346\211\223\345\274\200", nullptr));
        pushButton_56->setText(QCoreApplication::translate("MainWindow", "2_\351\227\255\345\220\210", nullptr));
        pushButton_57->setText(QCoreApplication::translate("MainWindow", "2_\345\215\212\351\227\255", nullptr));
        pushButton_58->setText(QCoreApplication::translate("MainWindow", "8", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab), QCoreApplication::translate("MainWindow", "Tab 1", nullptr));
        label->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">\344\270\262\345\217\243\357\274\232</span></p></body></html>", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p>\346\263\242\347\211\271\347\216\207\357\274\232</p></body></html>", nullptr));
        comboBox->setItemText(0, QCoreApplication::translate("MainWindow", "COM1", nullptr));
        comboBox->setItemText(1, QCoreApplication::translate("MainWindow", "COM2", nullptr));
        comboBox->setItemText(2, QCoreApplication::translate("MainWindow", "COM3", nullptr));
        comboBox->setItemText(3, QCoreApplication::translate("MainWindow", "COM4", nullptr));
        comboBox->setItemText(4, QCoreApplication::translate("MainWindow", "COM5", nullptr));
        comboBox->setItemText(5, QCoreApplication::translate("MainWindow", "COM6", nullptr));

        comboBox_2->setItemText(0, QCoreApplication::translate("MainWindow", "9600", nullptr));
        comboBox_2->setItemText(1, QCoreApplication::translate("MainWindow", "115200", nullptr));

        port_turnon->setText(QCoreApplication::translate("MainWindow", "\346\211\223\345\274\200\344\270\262\345\217\243", nullptr));
        pushButton_40->setText(QCoreApplication::translate("MainWindow", "\345\205\263\351\227\255\344\270\262\345\217\243", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">\344\270\262\345\217\243\350\256\276\347\275\256</span></p></body></html>", nullptr));
        sent_telegram->setText(QCoreApplication::translate("MainWindow", "\345\217\221\351\200\201", nullptr));
        label_4->setText(QCoreApplication::translate("MainWindow", "\345\244\271\351\222\2631\357\274\232", nullptr));
        label_5->setText(QCoreApplication::translate("MainWindow", "\345\244\271\351\222\2632\357\274\232", nullptr));
        label_6->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p>\345\277\253\346\215\267\346\273\221\350\275\250\346\223\215\344\275\234\357\274\232</p></body></html>", nullptr));
        miniCamera_label1->setText(QCoreApplication::translate("MainWindow", "TextLabel", nullptr));
        miniCamera_label2->setText(QCoreApplication::translate("MainWindow", "TextLabel", nullptr));
        pushButton_38->setText(QCoreApplication::translate("MainWindow", "\345\276\256\345\236\213\347\233\270\346\234\272\345\274\200\345\205\263", nullptr));
        pushButton_39->setText(QCoreApplication::translate("MainWindow", "\345\217\226\346\265\201", nullptr));
        pushButton_41->setText(QCoreApplication::translate("MainWindow", "\346\230\276\347\244\272\345\247\277\346\200\201", nullptr));
        pushButton_42->setText(QCoreApplication::translate("MainWindow", "\346\240\241\346\255\243\345\247\277\346\200\201", nullptr));
        stop_button_2->setText(QCoreApplication::translate("MainWindow", "STOP", nullptr));
        pushButton_37->setText(QCoreApplication::translate("MainWindow", "Double_arms", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QCoreApplication::translate("MainWindow", "Tab 2", nullptr));
        Model_predict->setText(QCoreApplication::translate("MainWindow", "\346\250\241\345\236\213\351\242\204\346\265\213", nullptr));
        Py_initialize->setText(QCoreApplication::translate("MainWindow", "\345\210\235\345\247\213\345\214\226Py\347\216\257\345\242\203", nullptr));
        predict_pic1->setText(QCoreApplication::translate("MainWindow", "TextLabel", nullptr));
        predict_pic2->setText(QCoreApplication::translate("MainWindow", "TextLabel", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QCoreApplication::translate("MainWindow", "Tab3", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
